### ISSUE TITLE
Support referencing elements between different source files

### ISSUE THREAD

**Issue by jakub-plichta** [antlr/intellij-plugin-v4#104]
Current version supports navigating to element declaration within the same file. But I can split grammar into multiple files and then link them together in one master file using `import` statement:

```
import LexerRules, BasicElements, Addition, Misc;
```

Please extend navigation to declaration, find usage etc. to files linked together.

**Comment by sangohan** [comment]
i'd also like support for imports.

**Comment by n3wtn9** [comment]
+1

**Comment by domikrueger** [comment]
a possibly related problem is code completion: rules and tokens defined in the imported grammar do not show up in the auto completion drop down list when editing the importing grammar.

**Comment by bjansen** [comment]
Navigation & find usages are now available in master.
Code completion will come later.

**Comment by bjansen** [comment]
Code completion is already covered in #284, so I'm closing this one because navigation is done.
