### ISSUE TITLE
Comment/Uncomment shortcut key

### ISSUE THREAD

**Issue by jrguenther** [antlr/intellij-plugin-v4#149]
It would be awesome to be able to use &#8984; - / or control -/ on windows to toggle whether a line in the grammar is commented or not.

I looked through the keymap and plugin settings to see if there was an option, but couldn't find it.

I'd be happy to add the feature if you can point me to the part of the plugin code that handles the grammar editor.

**Comment by parrt** [comment]
Fixed in 2b5e0264b4bed5b3aa8a238341d8b7d73a067801.
