### ISSUE TITLE
Incorrect grammar file range highlighting when selecting items at the Profiler panel

### ISSUE THREAD

**Issue by LuizZak** [antlr/intellij-plugin-v4#159]
Currently, whenever I select an item on the Profiler's table view, the region selected on the grammar file does not match anything with any sort of precision, and you can't really understand *what* exactly it's trying to highlight.

I'm running Windows 7 x64, with the 1.6 plugin version on IntelliJ:
IntelliJ IDEA 14.0.4
Build #IC-139.1117 - JRE 1.8.0_25b18 x86

Here are some screen shots of the bug in action:

http://imgur.com/a/WP7E3

**Comment by parrt** [comment]
wow!  could i have the grammar?

**Comment by LuizZak** [comment]
Yeah sure, this is the .g4 file: https://gist.github.com/LuizZak/7f38d4b6b6c42e60b1ed

And this is the sample file I'm currently experiencing the bug on: https://gist.github.com/LuizZak/166f9684d18d4fa0d48a

I'm also noticing a crash being logged on the IDE when I select some of the last entries on the list:

> 13:52:54 NoSuchElementException: token index -1 out of range 0..2255

**Comment by parrt** [comment]
Thanks.  I hope to send out a release sometime soon.

**Comment by parrt** [comment]
Hi. I reset to plugin 1.6 and tried with 13.x, 14.x, java 1.7, 1.8. Can't reproduce on my mac I'm sorry to say.  plugin 1.7 seems ok too. can you try the new beta? http://www.antlr.org/download/intellij-plugin-v4-1.7b1.zip

**Comment by parrt** [comment]
Has this resolved itself?

**Comment by LuizZak** [comment]
I now this is an oldie, but just for historic purposes, I returned to the project and using the latest v1.8.4 version of the plugin the issue seems to be resolved!
