### ISSUE TITLE
Possible bug with preview

### ISSUE THREAD

**Issue by danilaml** [antlr/intellij-plugin-v4#161]
ANTLR 4.5, Idea 14.0.3
Situation: I have grammar. I generate parsers/lexers with it and print parse result into console System.out.println(tree.toStringTree(parser)
Problem : I have no errors/warnings, everything generates and compiles alright but on the same file result of generated antlr parser and tree in preview is different. (and it seems like the preview one is wrong)
Possible cause:
the problematic nodes/rules (that differ) are exactly the same except they have different semantic predicates. Something like this:
```
rules
 : (firstRule | secondRule)+ EOF
 ;

firstRule
 : {_input.LT(1).getText().contains("rule1")}? TextToken commonPart
 ;

secondRule
 : {_input.LT(1).getText().contains("rule2")}? TextToken commonPart
 ;

thirdRule
...
```

and file I parse is like this:
```
rule1 commonPart
rule2 commonPart
rule2 commonPart
```
but in preview it's all rule1

**Comment by parrt** [comment]
The interp can't execute actions or predicates. sorry.

**Comment by dmeehl** [comment]
What does this mean? The preview will always be wrong if you use semantic predicates?

**Comment by parrt** [comment]
absolutely. Interpreter cannot execute Java code or any other random language you include in the grammar as actions. sorry.
