### ISSUE TITLE
White text for parse tree labels using dark themes.

### ISSUE THREAD

**Issue by jjzazuet** [antlr/intellij-plugin-v4#170]
Small suggestion. Use white text for parse tree labels for Idea users working on dark themes.

![IntelliJ parse tree](https://db.tt/42fJyJbb)

Thanks! :+1:

**Comment by parrt** [comment]
Thanks. I will have to figure out how to get the current style and then tweak the text color.

**Comment by jjzazuet** [comment]
Much appreciated! :+1:  :)
