### ISSUE TITLE
generate psi

### ISSUE THREAD

**Issue by jasonnn** [antlr/intellij-plugin-v4#175]
It would be nice if antlr could generate a psi structure that matched the structure of the generated parse tree

**Comment by jasonnn** [comment]
My first thought was to have the generated RuleContexts extend a base class that implemented both ASTNode and PsiElement. 
ParserRuleContext can be extended to implement ASTNode but there are signature clashes with PsiElement. bummer.

**Comment by jasonnn** [comment]
Also, and this is probably more for antlr proper, an "annotation processor" spi/api for antlr might be nice so that additional analysis/codegen can be done at build-time without having to write  custom code to bootstrap the compilation/generation process.

**Comment by parrt** [comment]
I was thinking sort of along the same lines but completely disengaging from the psi structure as it doesn't really buy me much when ANTLR already knows how to parse and syntax highlight and highlight errors in the preview window. It can simply do so for itself, thus avoiding one of the scariest parts of intellij: the parser lecture framework.

**Comment by jasonnn** [comment]
parser lectures scare me too ;)

how about this...
```java
class AntlrASTRuleContext extends ParserRuleContext implements ASTNode {
    int siblingIndex=-1;  // need to get this from parent so that astnode next/previous sibling can be implemented semi-efficiently ...

    @Override
    public AntlrPsiElement getPsi();
   //specialize the return type of other methods to return AntlrASTRuleContext instead of ASTNode...
}

public class AntlrPsiElement extends ASTWrapperPsiElement{
    public AntlrASTRuleContext getNode() {
        return (AntlrASTRuleContext) super.getNode();
    }
}
```
and then use it like so
```java
public PsiElement someApi(PsiElement element){
   AntlrASTRuleContext ctx = ((AntlrPsiElement) element).getNode();
   //use antlr specific stuff here
   return ctx.getPsi()   
}
```
while this isn't super awesome, I think its an 'eh, alright' compromise between ignoring the psi completely and totally committing to using it. 

Also, im assuming that PsiBuilders are simply helper classes and don't need to be used to construct the tree.

**Comment by parrt** [comment]
hahaha. yeah, voice-recognition error.

One problem we have is that ANTLR 4 does not allow you to specify a treenode factory :(

**Comment by jasonnn** [comment]
This is pretty hackey but i was thinking of just using a modified Java stg to make the base-type change. 

I think the PsiBuilder would have to be adapted back info a TokenStream and possibly an error listener too.

**Comment by parrt** [comment]
not a bad idea :)

**Comment by jasonnn** [comment]
I've been working in [this branch](https://github.com/jasonnn/intellij-plugin-v4/tree/psi) to try and implement this. I've worked out most of the stupid obvious bugs, and it's producing an ast/psi that looks more or less correct. There's three main issues, though:
* something is causing ideas indexing system to go nuts and loop forever.
   - this one is kind of a biggie as it breaks the entire ide and will cause thigh burns if you're testing on a laptop
* hidden tokens are hidden (what?!). we need a way to add comments and whitespace to the parse tree.
* many methods are still unimplemented/poorly implemented.

anyways, I just wanted to keep you in the loop. Hopefully ill have this all worked out soon.

**Comment by parrt** [comment]
ok, thanks.  I wouldn't put too much work into this until I have a chance to really evaluate the direction. Unfortunately I'm slammed until probably end of March :(

**Comment by parrt** [comment]
I'm beginning to think that I'm going to create my own text editor window that knows how to do syntax highlighting and all of the usual junk but specifically based upon an ANTLR grammar rather than their psi stuff. Their lexer stuff freaks me out and I get random errors out of it. I'm not sure going down the path of psi is the right answer. If necessary, one could simply make a psi tree by walking the parse tree. For now, I'm going to close this issue so I can appear to make headway on my bug list ;)

**Comment by jasonnn** [comment]
In case you get stuck, I think the markdown plugin (https://github.com/nicoulaj/idea-markdown) does this.

**Comment by parrt** [comment]
thanks!

**Comment by Lordfirespeed** [comment]
Could we re-open this? Even if it's just a case of adding some documentation explaining how someone *could* generate PSI classes.

**Comment by Lordfirespeed** [comment]
Actually, leaving this here for future people in my position - You do not need to generate PSI classes. You can use the [antlr-intellij-adaptor](https://github.com/antlr/antlr4-intellij-adaptor/) project to adapt Antlr's AST. An example of this can be seen [here](https://github.com/antlr/jetbrains-plugin-sample/blob/master/src/main/java/org/antlr/jetbrains/sample/SampleParserDefinition.java)
