### ISSUE TITLE
Negative lookahead problems

### ISSUE THREAD

**Issue by Botev** [antlr/intellij-plugin-v4#176]
I'm building a matlab parser and have the following rule:
STRING
	: {!(""+((char)_input.LA(-1))).matches("[a-zA-Z0-9\\])}]")}? '\'' (ESC_SEQ | ~('\\'|'\''|'\r'|'\n') )* '\''
	;
Which is because of the matlab usage of singel quote for strings as well as transpose. The problem is that invoked torugh java this parses the following program correctly:
function sad = a(varargin)
a = b'*c + d'*f;
end
However in the plugin preview it gives me the following error:
line 2:5 extraneous input ''*c + d'' expecting {'==', '||', '&&', '<=', '>=', '~=', '.*', './', '.\\', '.^', '.\'', '|', '&', '<', '>', ':', '+', '-', '*', '/', '\\', '^', '\'', ';', '(', '{', '.', ','}
Which means that it is trying to create the STRING token, however in normal java works, so my guess is something is wrong with the plugin on some level.

**Comment by parrt** [comment]
'\' must be '\\'

**Comment by Botev** [comment]
That was in fact a paste mistake seems like the editor converted '\\' to '\' on the ctrl+c -> ctrl+v (if I understood that you mean in the brackets after ESC_SEQ). Also again I emphasis that it works without any errors from the java class invocation. If you want I can send down the whole grammar + files to examine the issue (if you will have also) directly?

**Comment by parrt** [comment]
Ok, perhaps I should point out that the plug-in interpreter can execute Java code? ;) If you expect that predicate to execute it will not do so during live preview just when you actually execute a generator parser.

**Comment by Botev** [comment]
Okay that makes sense, I downloaded ANTLRWorks anyway as the graph view is slightly better. Just to ask if I want to contribute by providing the grammar (if and when its finished) who should I contact? (Tbh I don't want to host it myself and I saw a repo with quite a few already done grammars).

**Comment by parrt** [comment]
you can post your grammar to  https://github.com/antlr/grammars-v4 with a pull request :)

 by graph you do you mean the fact that ANTLRWorks has a syntax diagram view where my plug-in does not?

Thanks, Ter

**Comment by Botev** [comment]
No your plugin has, but the whole java panel scroll zooming  (which I think is a java issue) is not too good for larger trees (e.g. when you zoom it goes to the left instead of keeping the focus on the middle)  and the vertical scroll is too slow on mouse button scrolls. Call me fastidious, but for a larger tree it takes me about a minute just to get closer to my goal. Also another java problem (which the ANTLRWorks also have) - you can't search for strings in the panel, would make your live 10 times easier. 
Anyway I think the integration is great of the plugin, potentially also might be worth to have some way of automatically putting the antlr jar on the classpath (maybe like adding a facet) .... 
Don't mind me btw, I still find it very usefull, and also just saw that on Linux the ANTLRWorks have some problems with java and with the bourne shell, so IntelliJ is better.
All the best!
