### ISSUE TITLE
Parse tree in plugin is different from tool

### ISSUE THREAD

**Issue by robertical** [antlr/intellij-plugin-v4#180]

**Comment by robertical** [comment]
I tried this grammar and the error recovery in the plugin is different from the one I get using the testrig. I got my grammar simplified to reproduce the issue.

the input is the text inside the quotes
":XXX"

The plugin seems to recover as I was hoping while writing the grammar, but when I use the grammar in the real life, the recovery is different and it doesn't seem to sync. Also the error messages I get are different:
My app => line 1:0 no viable alternative at input ':'
plugin => line 1:0 extraneous input ':' expecting {'(', Term}


grammar Combined1;

compileUnit :	field EOF	;

field:		fieldName ':' value
	|	value 
;

fieldName: Term;

value:	'(' value ')'
	|	Term
; 

/* Lexer Rules */
Term:	TERM_START_CHAR TERM_CHAR*;
fragment TERM_START_CHAR:   ~( ' ' | '\t' | '\n' | '\r' | ':' );
fragment TERM_CHAR : (TERM_START_CHAR | '.' );
WS  :	[ \t\r\n\f]+ -> skip;



![intellij](https://cloud.githubusercontent.com/assets/1840489/7081706/10981790-df8a-11e4-8ae1-e75d520d984a.png)
![testrig](https://cloud.githubusercontent.com/assets/1840489/7081707/109944da-df8a-11e4-93dd-f19771b69baf.png)

**Comment by robertical** [comment]
Any ideas about why this could happen?
Plugin recovery seems way better than Standard recovery in ANTLR4.
Is there a way to get the recovery from the plugin into our code?

**Comment by parrt** [comment]
Strange. should be same but generated code might use some statically-computed info the interp doesn't in plugin. wait. is your parser calling field not compileUnit? sounds likely.

**Comment by robertical** [comment]
I'm calling the same compileUnit, the tree on the left shows the tree.
On the right it shows field because I probably clicked and selected the "field" node on the left hand side.

I've found the same issue in 2 other grammars, but for simplicity I stripped out all the extra stuff so I could post a very simple grammar that shows the issue.
If the text to parse is correct, I always get the right tree. It's only the recovery part that the plug-in does a better job.

**Comment by robertical** [comment]
Has anybody had a chance to look at this issue?

**Comment by parrt** [comment]
Soon. Next week is the last week of school

**Comment by parrt** [comment]
Hi. please set LL_EXACT_AMBIG_DETECTION mode in your non-plugin app and see if you get same tree.

```java			parser.getInterpreter().setPredictionMode(PredictionMode.LL_EXACT_AMBIG_DETECTION);
```

def is:

```java
	/**
	 * The LL(*) prediction mode with exact ambiguity detection. In addition to
	 * the correctness guarantees provided by the {@link #LL} prediction mode,
	 * this prediction mode instructs the prediction algorithm to determine the
	 * complete and exact set of ambiguous alternatives for every ambiguous
	 * decision encountered while parsing.
	 *
	 * <p>
	 * This prediction mode may be used for diagnosing ambiguities during
	 * grammar development. Due to the performance overhead of calculating sets
	 * of ambiguous alternatives, this prediction mode should be avoided when
	 * the exact results are not necessary.</p>
	 *
	 * <p>
	 * This prediction mode does not provide any guarantees for prediction
	 * behavior for syntactically-incorrect inputs.</p>
	 */
```

**Comment by parrt** [comment]
It might also be that we do only "fail and bail" error recovery in interp vs gen'd parser. I.e., no single token insertion/deletion recovery; just fail rule, recover to follow set, continue. Interp is not going to give exact same results for bad input.

**Comment by marcospassos** [comment]
Guys,

I can confirm this bug in the latest version. Where the IDE shows `extraneous input ')'` the testrig shows `missing ')'`. Is there any way to keep it consistent?

**Comment by marcospassos** [comment]
@parrt,

I can confirm this bug in the latest version. Where the IDE shows extraneous input ')' the testrig shows missing ')'. Is there any way to keep it consistent?

**Comment by parrt** [comment]
hi. not sure. will look when I can. plugin uses an interpreter rather than generated code. strange!

**Comment by marcospassos** [comment]
To give you a landscape, given an ordinary grammar (such as JS, PHP, etc),
we're trying to parse the following invalid code: `a(|b)`.
While the plugin recognizes it as a function call, discarting the `|` token
(`a(b)`), the testrig recognizes it as a binary bitwise expression (`a |
b`), discarting the `(` and `)` after recovering from the error.

Is it just an edge case or is there any way of the plugin being performing
a _better_ error recovery? I've no clue how the plugin's recovery strategy
can be better once both share the same logic. Besides the fact being
interpreted or generated, I believe that should exist some cases where
the recovering strategy of the plugin should perform worst in counterpart.

Em sexta-feira, 9 de setembro de 2016, Terence Parr <
notifications@github.com> escreveu:

**Comment by marcospassos** [comment]
To give you a landscape, given an ordinary grammar (such as JS, PHP, etc),
we're trying to parse the following invalid code: `a(|b)`.
While the plugin recognizes it as a function call, discarding the `|` token
(`a(b)`), the test ring recognizes it as a binary bitwise expression (`a |
b`), discarding the `(` and `)` after recovering from the error.

Is it just an edge case or is there any way of the plugin being performing
a _better_ error recovery? I've no clue how the plugin's recovery strategy
can be better once both share the same logic. Besides the fact being
interpreted or generated, I believe that should exist some cases where
the recovering strategy of the plugin should perform worst in counterpart.

**Comment by marcospassos** [comment]
I've found more 5 cases where the tree generated by the IntelliJ plugin diverges from the one generated by the TestRig. In all cases, the results generated by the TestRig are much better by far.

@parrt Could you please reopen this issue? I'm really interested in improve the error recognition in the compiler we're working on. There is something in how theses errors are handled in the interpreter that makes it significantly smarter than TestRig.

**Comment by parrt** [comment]
Happy to reopen, but I could really use a sample grammar and input to help me track this down.

**Comment by marcospassos** [comment]
Hi @parrt, nice to see you around!

Grammar:

```antlr
grammar TestGrammar;

expression
    : durationExpression EOF
;

durationExpression
    : durationYear
;

durationYear
    : INTEGER durationYearSuffix
;

durationYearSuffix
    : ('year' | 'years') durationMonth?
    | durationMonthSuffix
;

durationMonth
    : INTEGER durationMonthSuffix
;

durationMonthSuffix
    : ('month' | 'months') durationWeek?
    | durationWeekSuffix
;


durationWeek
    : INTEGER durationWeekSuffix
;

durationWeekSuffix
    : ('week' | 'weeks')
;

INTEGER: [0-9]+;

WHITESPACE
    : (' ' | '\n' | '\t' | '\r' )+ -> channel(HIDDEN)
;
```

Input:
```js
1 months 1 years weeks
```

Result on IntelliJ:
It's smartly recognized. It understand that there is an extraneous `year` token and matches the next token that's correct.

![image](https://cloud.githubusercontent.com/assets/943036/20034434/52326aee-a3a5-11e6-81e7-1f20c2a60a8c.png)

Result on TestRig:
In TestRig, the parser isn't able to recognize that discarding the `year` the input becomes valid, raising a `NoViableAltException`:

```
grun TestGrammar expression -diagnostics -tree
1 year 1 year month
line 1:9 no viable alternative at input 'year'
(expression (durationExpression (durationYear 1 (durationYearSuffix year (durationMonth 1 (durationMonthSuffix year month))))) <EOF>)
```

Does it help? It would be very helpful delivery a first version of our parser contemplating the same error recovery mechanism that we can find on IntelliJ.

**Comment by parrt** [comment]
Confirming output above with 4.5.3 and `grun`. Confirming plugin output. Investigating.

**Comment by parrt** [comment]
Ok, @robertical i've boiled down to trivial grammar:

```
grammar TestGrammar;

a : A | {} B ;  // {} prevents A|B from becoming set.

A : 'a' ;
B : 'b' ;
C : 'c' ;

WHITESPACE : [ \n\t\r]+ -> channel(HIDDEN) ;
```

Plugin gives:

```
line 1:0 extraneous input 'c' expecting {'a', 'b'}
```

and `grun` gives:

```
line 1:0 no viable alternative at input 'c'
``

The `grun` output is what I'd expect. It is at a decision and the lookahead isn't consistent with either choice. It does not do token deletion correction during lookahead.

Ok, so the interpreter in plugin sync's before checking decisions in `visitDecisionState()`:

```java
getErrorHandler().sync(this);
```

code gen does not sync for LL(1) decisions:

```java
    public final AContext a() throws RecognitionException {
        AContext _localctx = new AContext(_ctx, getState());
        enterRule(_localctx, 0, RULE_a);
        try {
            setState(5);
            switch (_input.LA(1)) {
...
```

but does for LL(k>1) when i use `a : A X | {} A Y ;`:

```java
	public final AContext a() throws RecognitionException {
		AContext _localctx = new AContext(_ctx, getState());
		enterRule(_localctx, 0, RULE_a);
		try {
			setState(7);
			_errHandler.sync(this);
			switch ( getInterpreter().adaptivePredict(_input,0,_ctx) ) {
...
```

@sharwell objections to injection of `sync()` call in LL(1) to make consistent?

**Comment by parrt** [comment]
Ok, For ANTLR 4.6, I get the improved results that match plugin:

```
line 1:0 extraneous input 'c' expecting {'a', 'b'}
```

I'll have to push a plugin version after 4.6 is out. I'll close this as it'll just fix itself in future.

**Comment by marcospassos** [comment]
@parrt thank you very much!

**Comment by marcospassos** [comment]
@parrt I can confirm that for the case I've provided it's working like a charm.

```
 grun TestGrammar expression -tree
1 year 1 year month
line 1:9 extraneous input 'year' expecting {'month', 'months', 'week', 'weeks'}
(expression (durationExpression (durationYear 1 (durationYearSuffix year (durationMonth 1 (durationMonthSuffix year month))))) <EOF>)
```

Thank you again!
