### ISSUE TITLE
Show token types in parsetree preview

### ISSUE THREAD

**Issue by aivarannamaa** [antlr/intellij-plugin-v4#181]
Creating overlapping lexer rules is one of the most common mistakes my students make when writing ANTLR grammars. If parse tree preview pane showed which rule was used for producing the token (eg. when hovering the mouse over the token), they would more likely find the mistake themselves. 

Alternatively (or additionally) command line ANTLR could say eg. "Excpected INT but got DOUBLE" instead of just "Expected INT".

**Comment by parrt** [comment]
Hi.  it already does that. Hold down one of the meta-keys and you will see all sorts of fun things. :)

**Comment by aivarannamaa** [comment]
Did you mean these fun things can only be seen on a Mac? I tried holding down Shift, Alt, Control and combinations of these in Windows, but nothing happened.

**Comment by parrt** [comment]
hahahah! Ok, sounds like I have to get a windoze VM loaded and try this out. what are the meta keys on a windows machine supposed to be?

**Comment by aivarannamaa** [comment]
I would choose Ctrl key for this In Windows. (Alt key is used to show or open menus, so this wouldn't be ideal). What do you think about adding a toggle button or checkbox as alternative means for showing this extra information?

**Comment by parrt** [comment]
I should probably just make it use control all the time on Windows ;I think it's the only place I use the meta-key

**Comment by parrt** [comment]
can you email me directly to get a zip to try out? parrt@antlr.org
