### ISSUE TITLE
More syntax highlighting options for parser rule labels

### ISSUE THREAD

**Issue by superraz375** [antlr/intellij-plugin-v4#185]
It would be nice to have more syntax highlighting options besides just `Lexer Rule` and `Parser Rule`.
For example, I find it helpful to distinguish the `Rule Element Labels` the way it is implemented in AntlrWorks2 (As seen in the picture below)

Current version of IntelliJ plugin
![current](https://cloud.githubusercontent.com/assets/1769935/7821231/f227f81e-03b2-11e5-98a3-d76f5178cd78.PNG)

AntlrWorks2
![request](https://cloud.githubusercontent.com/assets/1769935/7821130/42247f6e-03b2-11e5-9176-e8a10dbfaf03.PNG)

**Comment by parrt** [comment]
Ah. good point.

**Comment by parrt** [comment]
whoops. that's not possible in intellij using standard lib. They can only colorize using that config dialog based upon the token but only the parser knows if it's a label. x=y could be an option or whatever. :(

**Comment by superraz375** [comment]
No problem, that makes sense. Thank you for looking into it!
