### ISSUE TITLE
Update Intellij plugin repository with latest build

### ISSUE THREAD

**Issue by slimjim2234** [antlr/intellij-plugin-v4#191]
Could you please update the intellij plugin repository with the latest build?  The latest version of the antlr plugin is dated January 12, 2015.
Thanks.

**Comment by parrt** [comment]
Yup.  just trying to finish off 1.7. Are you willing to try a beta?

**Comment by parrt** [comment]
Please try [1.7b1](http://antlr.org/download/intellij-plugin-v4-1.7b1.zip)
