### ISSUE TITLE
Format README.md

### ISSUE THREAD

**Issue by Suseika** [antlr/intellij-plugin-v4#192]
Readme is hard to read, please format it properly. The main nuissance is the lack of lists.

**Comment by parrt** [comment]
What's wrong? How about a Pull Request? ;)  Looks great to me.

**Comment by Suseika** [comment]
@parrt Here is a pull request. I came here after trying to read the plugin description in IntelliJ IDEA settings. That is basically a wall of text, what is shown there : ) I think it would be great if it is split into items.
