### ISSUE TITLE
Cannot load project

### ISSUE THREAD

**Issue by nedimmuminovic** [antlr/intellij-plugin-v4#199]
After restarting IDE I get the following error:
"Cannot load project: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: org.antlr.intellij.plugin.ANTLRv4PluginController PluginClassLoader[org.antlr.intellij.plugin, 1.7] [Plugin: org.antlr.intellij.plugin]"

Java version: 8 Update 51

**Comment by parrt** [comment]
wow!  Which version of intellij? Won't work with 15 yet.

**Comment by nedimmuminovic** [comment]
Version:
14.1.4

**Comment by parrt** [comment]
weird. Have you tried unisntalling then reinstalling plugin?

**Comment by nedimmuminovic** [comment]
Made a fresh installation of IntelliJ and plugin.
Still doesn't work.

**Comment by parrt** [comment]
hmm...maybe blast your preferences for intellij in your ~/Library?  Maybe use java 7 for intellij?

**Comment by parrt** [comment]
Hi.  any luck getting this to work? Unless you can get me the log file or something I won't be able to figure this out.

**Comment by nedimmuminovic** [comment]
It works after software updates.
Current versions:
Intellij 15.0 Community edition
java 1.8.0.65

**Comment by parrt** [comment]
great! ok, closing.
