### ISSUE TITLE
"new" icons look bad in IDEA's "dark mode"

### ISSUE THREAD

**Issue by Buesing-Sebastian** [antlr/intellij-plugin-v4#200]
Hi, title pretty much says it all. Icons should have transparency instead of white background.
![bildschirmfoto 2015-07-22 um 14 26 47](https://cloud.githubusercontent.com/assets/636037/8825229/b930802e-307d-11e5-9577-5151bd6b4835.png)

**Comment by parrt** [comment]
yeah, i couldn't figure out how to get transparent background. can you do a PR?

**Comment by parrt** [comment]
I think somebody submitted a patch; it's fixed now for upcoming 1.8. ![screen shot 2015-11-03 at 9 48 38 am](https://cloud.githubusercontent.com/assets/178777/10916376/1531b08a-8210-11e5-94da-c8adcab5e97e.png)
