### ISSUE TITLE
Release the adaptors as a standalone library

### ISSUE THREAD

**Issue by ftomassetti** [antlr/intellij-plugin-v4#216]
Hi, I think I am not the only one who would be extremely happy to reuse ANTLR grammars to create IntelliJ pluging. This plugins contain wonderful adaptors which I am currently ~~stealing~~ "taking inspiration from" to create an IntelliJ plugin.

However if this library was released we could reuse it more properly and build some documentation around it. I would be more than happy to help doing that if you think it is a good idea. In my opinion it would benefit both ANTLR users and IntelliJ aficionados.

**Comment by parrt** [comment]
Hi. Someone is also working on that at the moment.  I will ping them and asked them to look at this feature request.

**Comment by parrt** [comment]
@ftomassetti I'm building a new plugin based purely on ANTLR parse trees. From it we could create a generic plugin for any antlr grammar. please check out https://github.com/antlr/jetbrains-plugin-st4. Want to help?

**Comment by ftomassetti** [comment]
great news! As soon as I find the time I will take a look at it and try use it in the plugin for my language

**Comment by parrt** [comment]
cool.  I'll make a repo and make you a collaborator. Ok, done. jump to https://github.com/antlr/jetbrains I'll add my development notes as doc too
