### ISSUE TITLE
Graphical Glitches on OS X With Retina Display

### ISSUE THREAD

**Issue by absolutesantaja** [antlr/intellij-plugin-v4#218]
I've attached a couple of glitches I'm running into on IntelliJ 14.1.4 Ultimate. I'm running the latest 1.7 version of the plugin. Since these are only affecting this plugin I'm not sure if it's a plugin bug or IntelliJ's. First issue is Preview Input/File Box is cut off and the second is the popup error messages are repeated for the same line over and over again.
<img width="1440" alt="screen shot 2015-09-23 at 8 30 49 am" src="https://cloud.githubusercontent.com/assets/9768773/10047314/305d03a8-61d3-11e5-9eb9-d66ce3e699d1.png">
<img width="1440" alt="screen shot 2015-09-23 at 8 30 58 am" src="https://cloud.githubusercontent.com/assets/9768773/10047315/30774e5c-61d3-11e5-9be0-ab261b0929e3.png">

**Comment by parrt** [comment]
gross! I'll have to look on my laptop or work machine. Is it Java 6? 7? 8?

**Comment by absolutesantaja** [comment]
It's the most current version of 8. Not sure on the revisions but I can check when I get home.

Thanks

Sent from my iPhone

On Nov 2, 2015, at 12:45 PM, Terence Parr <notifications@github.com<mailto:notifications@github.com>> wrote:


gross! I'll have to look on my laptop or work machine. Is it Java 6? 7? 8?

-

**Comment by parrt** [comment]
hopefully it's easy to reproduce :) tracking a IDEA 15 incompatibility now :(

**Comment by parrt** [comment]
The repeated errors I think I've fixed btw

**Comment by parrt** [comment]
Actually, "Preview Input/File Box is cut off". how so? too narrow? Yeah, same for me. needs wide layout. can you check that?
