### ISSUE TITLE
Text window doesn't clear errors upon grama or program change

### ISSUE THREAD

**Issue by wstrzalka** [antlr/intellij-plugin-v4#237]
If you enter your 'program' as a text in ANTLR Preview window and there are errors, parts of 'program' are highlighted in red with error messages as a tooltip. 
If the errors come from bad gramma, after you fix the grammar the tree is redrawn but the errors are not being cleared (or reevaluated at all).
The same happens if you write your program not in a sequence - assume you have rule that recognizes sequence
(X) 
If you start typing X it will result in an error, if you add brackets later on the tree will get fixed but X will stay highlighted in red with error.

Workaround is to CUT & PASTE back the text window content.

I'm using IntelliJ Ultimate 14.1.5 & ANTLR plugin 1.7

**Comment by wstrzalka** [comment]
![antlr](https://cloud.githubusercontent.com/assets/2608256/11169425/b1e00cd2-8bb7-11e5-9ff8-86ab61a57df0.png)

**Comment by parrt** [comment]
Hi. please upgrade to 1.8 :)  it's fixed.
