### ISSUE TITLE
Root rules should not be highlighted as "unused parse rule"

### ISSUE THREAD

**Issue by KvanTTT** [antlr/intellij-plugin-v4#243]
Also discussion is here: https://github.com/antlr/antlr4/issues/1069

**Comment by yegorpetrov** [comment]
I don't think it's even possible to decide whether a rule is used or unused without analyzing the generated code. So may be there should be some special highlighting for "top-level rules". That could be enough of a hint for grammar developers without being false positive about use.

**Comment by parrt** [comment]
Any rule can be start symbol so no way to turn off grey squiggly. it's more useful to have than not so i'll close. thanks though!

**Comment by Enerccio** [comment]
maybe add a comment like // toplevel that would turn the spurious warning?

**Comment by MrCoder** [comment]
> maybe add a comment like // toplevel that would turn the spurious warning?

https://eslint.org/docs/2.13.1/user-guide/configuring#disabling-rules-with-inline-comments This is how eslint handles it.

**Comment by KvanTTT** [comment]
@MrCoder "Page not found". Could you please update the link and add its content to the comment?

**Comment by bjansen** [comment]
In Java it's possible to use `//noinspection <Inspection name>`, I'll see if it's possible to have the same thing in ANTLR.
