### ISSUE TITLE
Icon looks blurry on Retina display

### ISSUE THREAD

**Issue by electrum** [antlr/intellij-plugin-v4#244]
When using a Retina display on Mac, the icon looks blurry (compared to most other icons in IDEA that were updated to have Retina versions).

<img width="107" alt="screen shot 2015-12-21 at 9 01 30 am" src="https://cloud.githubusercontent.com/assets/9230/11936251/770d3500-a7c1-11e5-9cd2-aebb1d8cb256.png">

**Comment by parrt** [comment]
ok, got a decent retina icon now. Fixed in https://github.com/antlr/intellij-plugin-v4/commit/c1f7026eeff9bbedf3d527f0a7c284354029a74b

**Comment by parrt** [comment]
![antlr 2x](https://cloud.githubusercontent.com/assets/178777/15796333/ffc3d022-29b0-11e6-9378-93fbf57f9f53.png)

**Comment by parrt** [comment]
non-retina: ![antlr](https://cloud.githubusercontent.com/assets/178777/15796339/0571bb9c-29b1-11e6-98f9-c887bab19f6c.png)
