### ISSUE TITLE
Parse tree preview not working when parser/lexer files separated

### ISSUE THREAD

**Issue by virl** [antlr/intellij-plugin-v4#256]
When parser and lexer grammar reside in separate files, Parser tree preview is not working — it shown message "Issues with parser and/or lexer grammar(s) prevent preview; see ANTLR 'Tool Output' pane".

But Tool Output is empty too.

Grammars:
```
lexer grammar TwineLexer;

TAG_OPEN: '<<' -> pushMode(TAG);

LINK_OPEN: '[[' -> pushMode(LINK);

TEXT: TEXT_CHAR+;
fragment TEXT_CHAR
: ( '<' ~('<' | '\r' | '\n') )
| ( '>' ~('>' | '\r' | '\n') )

| ( '[' ~('[' | '\r' | '\n') )
| ( ']' ~(']' | '\r' | '\n') )

| ~('<' | '>' | '[' | ']' | '\r' | '\n')
;

NEWLINE
    :   (   '\r' '\n'?
        |   '\n'
        )
        -> skip
    ;

mode TAG;

TAG_CLOSE: '>>' -> popMode;

mode LINK;

LINK_CLOSE: ']]' -> popMode;

LINK_BAR: '|';

LINK_TEXT: TEXT_CHAR+;
fragment LINK_TEXT_CHAR
: ( '<' ~('<' | '\r' | '\n' | '|') )
| ( '>' ~('>' | '\r' | '\n' | '|') )

| ( '[' ~('[' | '\r' | '\n' | '|') )
| ( ']' ~(']' | '\r' | '\n' | '|') )

| ~('<' | '>' | '[' | ']' | '\r' | '\n' | '|')
;
```
```
grammar TwineParser;

options { tokenVocab=TwineLexer; }

node: link*;

link: LINK_OPEN (linkName LINK_BAR)? linkDest LINK_CLOSE;
linkName: LINK_TEXT;
linkDest: LINK_TEXT;
```

**Comment by virl** [comment]
Everything start to work if I add “parser” keyword before “grammar” for parser grammar.

But, nevertheless, it's a bug that plugin doesn't output anything to Tool Output window.

**Comment by parrt** [comment]
`grammar TwineParser;` means not separated.  The message saying "issues with grammar" is correct right?

**Comment by occipita** [comment]
*The message saying "issues with grammar" is correct right?* -- yes, but the part of the message that says "see ANTLR 'Tool Output' pane" is very misleading, as there is nothing on the Tool Output pane that is useful in diagnosing the cause of the issue.
