### ISSUE TITLE
IDE OOM crash when trying to test rule that matches the empty string

### ISSUE THREAD

**Issue by yawkat** [antlr/intellij-plugin-v4#260]
Plugin version: 1.8

IntelliJ IDEA 2016.1
Build #IU-145.970, built on April 18, 2016
JRE: 1.8.0_76-release-b47 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

---

I have the following grammar:

```
grammar template;

WS: ' ';

Literal: ~(' ')*?;
SubExpression: '*'? '${' Sequence '}';

Parameter: Literal?;// (SubExpression Literal)*;
Sequence: Parameter;// (WS Parameter)*;

sequence: Parameter;
```

I am testing the `sequence` rule. When typing any letter in the preview input, the IDE freezes and after a while crashes with an out-of-memory message.

I tracked allocations with yourkit and got this trace for the objects: ![Screenshot](https://s.yawk.at/eRfU.png)

This does not appear to happen when I change the `Literal` rule to not match the empty string.

This is a very annoying issue and currently prevents any kind of use of that feature.

**Comment by parrt** [comment]
Yeah, empty lexer rules are not valid. what does nothing match? everything? nothing?  i think we have trouble identifying all situations so hard to give an error. so, an antlr issue really; closing.
