### ISSUE TITLE
support for empty String ("") in locals

### ISSUE THREAD

**Issue by bintom** [antlr/intellij-plugin-v4#262]
When a locals block contain an empty Java string ("") grammar is recognized as invalid by mistake.

example:
<pre>
emptyRule 
  locals [String s="" /* starting from here the grammar is not coloured properly */] 
  :
;
</pre>

**Comment by parrt** [comment]
I can't reproduce. this seems fine:
<img width="208" alt="screen shot 2016-06-04 at 5 29 39 pm" src="https://cloud.githubusercontent.com/assets/178777/15802945/eea5455e-2a79-11e6-9c14-299303be67d9.png">

**Comment by bintom** [comment]
I made mistake by minimizing this example. The crucial thing is to add some quotes in an action code.

![error](https://cloud.githubusercontent.com/assets/19490746/15895153/0cd83e4c-2d8a-11e6-9c72-a3e531498c0b.PNG)

**Comment by parrt** [comment]
ah! ok, thanks. I will try to get this out for 1.8.1 coming out shortly.

**Comment by parrt** [comment]
Confirmed with this case:

```
parser grammar U;

a[String s=""]
  : A {f("");} B // <-- remove f("") and it's ok.
  ;
```
