### ISSUE TITLE
Test rule feature throws errors

### ISSUE THREAD

**Issue by nathanmerrill** [antlr/intellij-plugin-v4#267]
I'm unsure if this is a bug with ANTLR or the plugin, or if I don't understand something, but my guess is that this is an plugin bug.

If I create the following grammar:

    grammar Expression;`
    ZERO         : '0' ;
    NOTHING      : ZERO ;
    test         : NOTHING ;
    test2        : ZERO ;

Then test the rule `test` with input of `0`, I get the error `line 1:0 mismatched input '0' expecting NOTHING`, and the input `0` is underlined as an error.  However, the parse tree is still generated (and is correct).

However, if I test the rule `test2`, I don't get any errors.

**Comment by parrt** [comment]
only ZERO will ever match; see antlr4 book for discussion of ambiguous lexical rules :)
