### ISSUE TITLE
Add option to specify output directory relative to project root

### ISSUE THREAD

**Issue by wafisher** [antlr/intellij-plugin-v4#277]
Currently the option for specifying an output directory must be relative to the home directory, which obviously doesn't go well with projects that are developed by teams. The relevant code is [here](https://github.com/antlr/intellij-plugin-v4/blob/0ee6d19eb7088a033d1514a43de83c72d7e6ac17/src/java/org/antlr/intellij/plugin/configdialogs/ConfigANTLRPerGrammar.java#L56). When the default is used, it's relative to the `contentRoot` but when the user specifies a location, it's not.

I'd be happy to make the change and submit a PR. Let me know.

**Comment by parrt** [comment]
Hi. I think the intent is to let you set the dir to an absolute. Does that make sense?

**Comment by wafisher** [comment]
Yeah, but if I'm working on a team, the directory for me is `/Users/myName/pathWhereIStoreThisProject/generated-sources/` which is obviously different for others working on the team. Though not that I think about this maybe these settings aren't synced in our repo anyhow.

**Comment by parrt** [comment]
oh crap. hmm...ok, so if it starts with `/` then maybe absolute otherwise relative. make sense?

**Comment by wafisher** [comment]
Makes perfect sense.

**Comment by parrt** [comment]
Care to add yourself to contributors.txt and send PR?

**Comment by wafisher** [comment]
Will do.

**Comment by parrt** [comment]
Ok, i implemented. also does same trick for lib dir.
