### ISSUE TITLE
macOS10.12 idea2016.2.5 can't load the project after install the plugin

### ISSUE THREAD

**Issue by Haiming-Yang** [antlr/intellij-plugin-v4#281]
com.intellij.ide.plugins.PluginManger$StartupAbortedException
![2016-10-21 8 22 02](https://cloud.githubusercontent.com/assets/13255532/19598241/64128c2e-97cc-11e6-818e-ebe2fb14d623.png)

**Comment by parrt** [comment]
weird. did you find any exception trace I can look at?

**Comment by parrt** [comment]
@Haiming-Yang any log info or anything? I can't solve anything with just this info.
