### ISSUE TITLE
Channel definition not working

### ISSUE THREAD

**Issue by fdeitelhoff** [antlr/intellij-plugin-v4#285]
Hi there,

until the last plugin update I used the following channel definition in ANTLR4 with IntelliJ:

`channels {
    WHITESPACE,
    COMMENT
}`

After the update there's the following error:

error(50): SimplexLexer.g4:8:1: syntax error: 'channels {' came as a complete surprise to me while looking for an identifier

Did I missed a change log entry? Or what could cause that error.

Thank you
Fabian

**Comment by parrt** [comment]
I must not have updated the antlr parser in plugin ;) thanks!

**Comment by parrt** [comment]
The grammar in fact has channels in there. can you attach your sample file?

**Comment by parrt** [comment]
Works for me. Are you sure it's a `lexer grammar`?

**Comment by fdeitelhoff** [comment]
@parrt See the attached file. Maybe I'm just missing out something very simple. It works before the update.

[SimplexLexer.g4.txt](https://github.com/antlr/intellij-plugin-v4/files/662030/SimplexLexer.g4.txt)

**Comment by fdeitelhoff** [comment]
@parrt I just updated the plugin to the new version. With the internal ANTLR version 4.6 everything is working fine at the moment. Thanks for your help.

**Comment by parrt** [comment]
woot! Thanks for the report tho, @fdeitelhoff !
