### ISSUE TITLE
the tokens file path is wrong in gradle project

### ISSUE THREAD

**Issue by todylu** [antlr/intellij-plugin-v4#286]
I define `options { tokenVocab = CSharpLexer; }` in the `CSharpParser.g4`. 

In gradle project, the files: `CSharpParser.g4` and `CSharpLexer.g4` are in `<prj>\src\main\antlr`.

After compilation, the tokens file path is `<prj>\build\generated-src\antlr\main\CSharpLexer.tokens`, but the plugin try to find it in `<prj>\gen\CSharpLexer.tokens`

After modify the configuration of antlr plugin, the scanning path is still wrong.

**Comment by parrt** [comment]
Can you send a snapshot of your config for ANTLR? Something is not specified correctly.

**Comment by parrt** [comment]
@todylu Actually, it looks like an issue with where ANTLR looks for .tokens. this is not an intellij plugin issue.
