### ISSUE TITLE
Antlr 4.6

### ISSUE THREAD

**Issue by pureconfig** [antlr/intellij-plugin-v4#287]
Will this plugin soon support the newly released Antlr 4.6 and the new C++ target?

Thanks!

**Comment by parrt** [comment]
Coming today or tomorrow :)

**Comment by marcospassos** [comment]
I just opened a new issue to remember about the Maven Plugin:
https://github.com/antlr/antlr4/issues/1533

**Comment by marcospassos** [comment]
Btw, amazing work, @parrt!

**Comment by parrt** [comment]
Glad to be of service, @marcospassos !
