### ISSUE TITLE
per-file code gen prefs shouldn't go in workspace.xml

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#289]
Vassili reports: Great tool, but workspace.xml is not the right place for saving its per-file code generation preferences. They are essentially build settings, so they should go into project settings tracked by a VCS, not into a personal preferences file. it looks like i’m not in control of this. I use this code:

```
PropertiesComponent props = PropertiesComponent.getInstance(project);
```

which stores stuff where it wants. I’ll leave a note in the issue but not sure how to fix.

**Comment by parrt** [comment]
See “Using PersistentStateComponent” and “Defining the storage location” sections at:

http://www.jetbrains.org/intellij/sdk/docs/basics/persisting_state_of_components.html

**Comment by bjansen** [comment]
I created a PR to fix that problem :)
