### ISSUE TITLE
IDEA Plugin doesn't agree with Maven Plugin on location of `.tokens` files

### ISSUE THREAD

**Issue by CAD97** [antlr/intellij-plugin-v4#293]
This is an issue when running separate `lexer grammar` and `parser grammar` (thus using `options { tokenVocab = MyLexer ; }`).

File Structure:

```
Project
| 📁 src
| | 📁 main
| | | 📁 antlr4
| | | | 📁 imports
| | | | 📦 some.package
| | | | | 📄 MyLexer.g4
| | | | | 📄 MyParser.g4
| 📁 target
| | 📁 generated-sources
| | | 📁 antlr4
| | | | 📦 some.package
| | | | | 📄 MyLexer.java
| | | | | 📄 MyParser.java
| | | | 📄 MyLexer.tokens
| | | | 📄 MyParser.tokens
| 📄 pom.xml
```

The configuration for each `.g4` is correct (`~` means path to project)

```
Output directory where all output is generated | ~\target\generated-sources\antlr4
Location of imported grammars                  | ~\src\main\antlr4\imports
Grammar file encoding; e.g., euc-jp            | UTF-8
Package/namespace for the generated code       | some.package
Language (e.g., Java, Python2, CSharp, ...)    | Java
```

The plugin looks for the `.tokens`s in the folder `~/target/generated-sources/antlr4/some/package`, but the maven plugin puts them in `~/target/generated-sources/antlr4`.

IMHO, it makes more sense for the `.tokens` to be generated in the corresponding package where the generated code is located. This means that projects with grammars in multiple packages will have the `.tokens` files in the folders alongside the generated sources, instead of flat in the root of the generated sources folder.

I've uploaded a zip of a minimal reproduction case to a GitHub Gist. Note that the ANTLR file configuration has a `~` in the paths rather than the path to the project (as I don't know where you're putting the project). https://gist.github.com/CAD97/d607d5b7965b640949c80e9ec3231830

As this is a disagreement between the IDEA plugin and the Maven plugin, I've created this bug on both repositories.
antlr/intellij-plugin-v4: https://github.com/antlr/intellij-plugin-v4/issues/293
antlr/antlr4/antlr4-maven-plugin: https://github.com/antlr/antlr4/issues/1593

**Comment by CAD97** [comment]
If the ANTLR source files are not put in a package, the plugin will find the Maven generated `.tokens` as both plugins end up at the same location for generation. This is the only way to get proper plugin behavior (error highlighting, test parsing) at this time.

**Comment by parrt** [comment]
It looks like mvn plugin generates to ${project.build.directory}/generated-sources/antlr4 with -o option which will write .tokens and oh wait. It uses a custom Tool that alters standard tool behavior to write generated code using dir structure it sees for .g4 files. Hmm...ok, so maven plugin differs from default on command line. I'm going to leave both and just make the intellij antlr plugin look in more places. That should solve both.

**Comment by CAD97** [comment]
OK, so just testing this again, and ran into some more ***weird*** behavior from the IDEA plugin.

Upon loading the [above linked mini-project](https://gist.github.com/CAD97/d607d5b7965b640949c80e9ec3231830), the plugin doesn't complain _at all_ about trying to find token definitions from the lexer. It _just works_, and you can complains about non-existing tokens correctly.

- Commenting out the entire lexer grammar _does not_ make it stop working.  
- Correcting the configured path on the `.g4` configuration panel _does not_ make it stop working.
<br/>

- Doing a `mvn antlr4:antlr4` finally makes the plugin catch up and realize that it doesn't see a tokens file.  
- At this point `mvn clean` to revert to the prior file structure _does not_ return to the phantom-working state.  
- Reloading the project _does not_ return to the phantom-working state.  
- Returning the `.g4` configuration to their invalid paths (beginning with `~` instead of `<path-to-project>`) _does not_ return to the phantom-working state.
<br/>

- Reloading the project _does_ return to the phantom-working state.  
- Running `mvn antlr4:antlr4` _does not_ make it stop working.  
- Commenting and uncommenting the `.g4`s _does not_ make it stop working.  
- Fixing the configuration paths _does not_ make it stop working.
<br/>

- Commenting and commenting either `.g4` makes it stop working, complaining it cannot find the tokens file.

I have no idea why this happens, but this behavior does impact the testing of the behavior described in this report. I can create a screen-cast of this happening if you want, but it won't even be noticable after you've made the IDEA plugin look in the place where the maven plugin puts the `.tokens` file, as it just works even without the `.tokens` file until it realizes it does indeed want the file. ¯\\\_(ツ)\_/¯

On a separate note, testing rules with `context menu > Test Rule` still works throughout this entire process, which means the plugin can still see the linked lexer just fine, even without the `.tokens` file. This _might_ be why and how the IDE hints work for a bit after loading in the project with invalid path information. IMHO the in-IDE errors/warnings should be consistent with the preview tool (as that's what _I_ use the plugin for). I've just stumbled into another case where this works in the other direction -- the in-IDE hints are correct but the preview errors out. I'll make a separate issue for that after this one is fixed (to make sure that fixing this doesn't just automagically cause it to be fixed), but if you want to look at it at the same time, it has to do with importing a partial lexer grammar from the imports folder as set up to support the maven plugin.

**Comment by parrt** [comment]
Thanks, @CAD97 I'll get to this once 4.7 antlr is out.

**Comment by parrt** [comment]
Ok, confirming mvn plugin shoves stuff in output dir not package subdir.

<img width="338" alt="screen shot 2017-04-06 at 3 20 53 pm" src="https://cloud.githubusercontent.com/assets/178777/24777928/b6ed691c-1adc-11e7-91c3-aaeb708a674c.png">

Preview from grammar works no sweat.

<img width="719" alt="screen shot 2017-04-06 at 3 23 11 pm" src="https://cloud.githubusercontent.com/assets/178777/24777980/fd67dc6a-1adc-11e7-8b32-9f8498d76332.png">

I don't think it looks for .tokens. It looks for the "nearest" lexer per this line:

```
options { tokenVocab = MyLexer ; }
```

Ok, yup:

```java
/** Try to load a LexerGrammar given a parser grammar g. Derive lexer name
 *  as:  
 *      V given tokenVocab=V in grammar or
 *      XLexer given XParser.g4 filename or
 *      XLexer given grammar name X
 */      
public static LexerGrammar loadLexerGrammarFor(Grammar g, Project project) {
```

So, it's ignoring .tokens for purposes of preview.

In pom.xml, I use `<sourceDirectory>src/main</sourceDirectory>` in antlr4-maven-plugin and **set nothing in config** of any grammar using the intellij plugin. I guess you shouldn't mess with config in two different systems?

**Comment by occipita** [comment]
I'm not sure why these has been closed as invalid.  I'm still seeing the behaviour as described on latest versions (IDEA plugin 1.20-2022, Maven plugin 4.12.0).  The Maven plugin issue has been closed with a suggestion that it should be fixed here.  I presume this can be fixed by changing the configuration of the IDEA plugin (I haven't tried this yet), but it really should work by default.
