### ISSUE TITLE
Allow to use predefined values in Configure ANT LR window

### ISSUE THREAD

**Issue by bintom** [antlr/intellij-plugin-v4#300]
I would like to define my output directory as follows: $PROJECT_DIR$\src\gen\java
instead of hardcoded path.

**Comment by bjansen** [comment]
This is now working on master. There's a catch though: IntelliJ will automatically show the full path when you reopen the grammar settings dialog, although it will correctly store `$PROJECT_DIR$/...` in `.idea/misc.xml`. It seems to be the standard behavior, I couldn't find how to change it.

Macros will automatically be expanded when the ANTLR tool is called (the `Generate ANTLR Recognizer` action). You can use any predefined macro, as well as the ones defined in `Preferences > Appearance & Behavior > Path Variables`.
