### ISSUE TITLE
Ability to configure AntLR defaults for every grammar in project

### ISSUE THREAD

**Issue by bintom** [antlr/intellij-plugin-v4#301]
It would be perfect to configure ANT LR recognizer defaults for every grammar in the workspace in one place. Currently I need to configure recognizer for every grammar, for every workspace what is very inconvinient when working with multiple grammars

**Comment by bjansen** [comment]
This has been fixed in https://github.com/antlr/intellij-plugin-v4/pull/366, which is available in 1.11
