### ISSUE TITLE
If start rule is not selected, sub-windows in ANTLT Preview overlap

### ISSUE THREAD

**Issue by tysonite** [antlr/intellij-plugin-v4#308]
Picture shows the issue:
![image](https://cloud.githubusercontent.com/assets/196535/25554340/84da0508-2cd3-11e7-8d58-be05cb039fb2.png)

**Comment by parrt** [comment]
Please just make your window bigger :) thanks.

**Comment by bjansen** [comment]
This was bothering me too so I fixed it anyway (but don't tell anyone 🤫).

![image](https://user-images.githubusercontent.com/281528/50572987-29a96400-0dcb-11e9-9d2b-cab933bfeef9.png)
