### ISSUE TITLE
Instructions for building plugin

### ISSUE THREAD

**Issue by AndreasVoellmy** [antlr/intellij-plugin-v4#310]
It would be great to have a README for developers of this plugin. It should answer questions like: how do you build this project? Are there configuration variables that need to be set locally? Any other dependencies? 

I ask because I cloned the project and opened in IntelliJ and I tried building and rebuilding and neither worked. I also don't see any run configurations that might be useful for building.

**Comment by parrt** [comment]
Fortunately we just moved to using gradle.  I added minimal notes to the readme but basically enable gradle, plugin development plugins from intellij preferences, add the gradle file via gradle tool pane then launch `runIde` task.
