### ISSUE TITLE
Add an option to avoid package line generation

### ISSUE THREAD

**Issue by yeputons** [antlr/intellij-plugin-v4#318]
It's possible to specify package in the `@header` section:

```
grammar Foo;

@header {
package com.example;
}
```

In that case, no `-package` option should be passed to `antlr4` at all, otherwise there will be two `package` lines in the resulting code. Currently the plugin only allows to change `-package`'s value, but not to omit it.

**Comment by bjansen** [comment]
Right, when you omit the package the plugin tries to outsmart you and tries to deduce a package name from the directory in which your grammar resides. That's fixable.
