### ISSUE TITLE
Show symbolic name for leaf tokens in Hierarchy view (patch provided)

### ISSUE THREAD

**Issue by alexkli** [antlr/intellij-plugin-v4#322]
It would be useful to show the symbolic name for a token in the hierarchy view, not just its text, to see what type of token was recognized.

Instead of

    "<text>"

label it

    <symbol-name>: "<text>"

While that information is available by `CTRL` hovering in the source input window, that's pretty hidden and not visible as part of the whole tree.

I provided a patch over in my fork https://github.com/alexkli/intellij-plugin-v4/commit/f3b514ee65117dacf7d3d2f38dd6193ddfddcda7 and the result looks like this:

![antlr-intellij-plugin-show-token-symbol-name-screenshot](https://user-images.githubusercontent.com/229022/34542462-87c968ee-f091-11e7-84c0-ae1326ca2c2c.png)

In this example, compare the two literals `'bar'` and `2.0`, which are of different token types `StringLiteral` and `DecimalLiteral`, something that was not visible in the tree before.

You can try out with the [1.8.4-alexkli](https://github.com/alexkli/intellij-plugin-v4/releases/tag/1.8.4-alexkli) build from my fork.

(Note that providing a pull request is a bit tricky since I had to make [some changes](https://github.com/alexkli/intellij-plugin-v4/commit/e55e9e6efc86c4aac24ebc289b7a463f57e21323) to the project setup on my branch before it worked for me. I am happy to rebase things for a PR if accepted.)

**Comment by parrt** [comment]
Can you send a PR? Don't forget to sign the contributors file

**Comment by bjansen** [comment]
I like this feature. Thanks!

**Comment by parrt** [comment]
@bjansen make sure to check that people are signing the contrib file. can you get another PR from @alexkli for this? thanks!

**Comment by bjansen** [comment]
I added him manually (is this equivalent to him signing the contrib file directly?).

**Comment by parrt** [comment]
he has to have a commit to make it a sig. if you add his, it's you signing ;)
