### ISSUE TITLE
Show microsecond decimal precision in Profiler tab (patch provided)

### ISSUE THREAD

**Issue by alexkli** [antlr/intellij-plugin-v4#323]
For small files or the individual rule timings, the current millisecond precision (which does not display any decimals) can be a bit too coarse, if results are all just 0 or 1.

Microsecond precision would be better. The information is already there, captured in nanoseconds, so it's just about the display in the UI.

I provided a patch over in my fork https://github.com/alexkli/intellij-plugin-v4/commit/6c7199e854f1bef5a8f70ec695837f06ca0dd036 which results in this:

![antlr-intellij-plugin-profile-microsecond-precision-screenshot](https://user-images.githubusercontent.com/229022/34542820-1223832a-f093-11e7-943b-d989008520ee.png)

Note the `Time` column as well as `Parse time` and `Prediction time` fields on the right.

You can try out with the [1.8.4-alexkli](https://github.com/alexkli/intellij-plugin-v4/releases/tag/1.8.4-alexkli) build from my fork.

(Note that providing a pull request is a bit tricky since I had to make [some changes](https://github.com/alexkli/intellij-plugin-v4/commit/e55e9e6efc86c4aac24ebc289b7a463f57e21323) to the project setup on my branch before it worked for me, and I made another change for #322 on the same branch. I am happy to rebase things for a PR if accepted.)

**Comment by parrt** [comment]
Can you send in a pull request?

**Comment by bjansen** [comment]
I cherry picked your commit in b6411a6b, thanks for your contribution!
