### ISSUE TITLE
Updating plugin to ANTLR-4.7.1

### ISSUE THREAD

**Issue by doon386** [antlr/intellij-plugin-v4#331]
I'm able to use the plugin with COMMUNITY 2018.1, however the plugin seems to use ANTLR-4.7.

The ability to configure the plugin to use another version of ANTLR would be really useful. If this only can be done by rebuilding the plugin build instructions for the plugin would be helpful.

**Comment by parrt** [comment]
Next release 1.9 will do this. Working on it now.
