### ISSUE TITLE
Support case insensitivity in grammar preview/test

### ISSUE THREAD

**Issue by dhait** [antlr/intellij-plugin-v4#337]
Some languages (like SQL) are case-insensitive.  Antrl docs discuss this at [https://github.com/antlr/antlr4/blob/master/doc/case-insensitive-lexing.md](
) 

Antlr plugin should support an option to enable case-insensitive parsing in the preview window using the "custom character streams approach".

**Comment by parrt** [comment]
Your lexer rules have to implement this so not really something for this plugin. sorry.
