### ISSUE TITLE
Lexer not recognized

### ISSUE THREAD

**Issue by sirgru** [antlr/intellij-plugin-v4#340]
I have 2 files, a parser called TheParser.g4 and lexer called TheLexer.g4, in the same folder, with IntelliJ opened in that folder. I'm still getting unrecognized lexing rules, even though test rig works. 

Idea 2018.2.2 Community 
Windows 7

**Comment by parrt** [comment]
Seems to work for me. I tried generating code and also jumped to definition from the parser into the lexer, but that was a recent update.  hopefully 1.9 will fix this so I'm closing.
