### ISSUE TITLE
“line 1:0 mismatched input '<EOF>' expecting 'hello'” when parsing Hello.g4

### ISSUE THREAD

**Issue by wsyzzz** [antlr/intellij-plugin-v4#342]
Hi, everyone. I'm using IntelliJ IDEA and antlr v4 grammar plugin to parse a grammar. But it throws “line 1:0 mismatched input '<EOF>' expecting 'hello'” and shows nothing in parse tree. I'll appreciate it a lot if anyone could give me some advice.
My grammar is:
`grammar  Hello;                   r : 'hello' ID;                        ID : [a-z]+;                     WS : [ \t\r\n]+ -> skip; `

<img width="942" alt="1" src="https://user-images.githubusercontent.com/9331302/45858433-eed96e00-bd8f-11e8-8300-ec6558d5b607.PNG">

PS: I'm sure about that my IDEA and antlr plugin are latest version.

**Comment by wsyzzz** [comment]
It's a simple question because I had no input. I should read the introduction rather than do "hello world" at the beginning.

**Comment by langziyuhao** [comment]
Hello, I have the same problem. Have you solved it?

**Comment by wsyzzz** [comment]
> Hello, I have the same problem. Have you solved it?

Because you just created the grammar rules but didn't give an input. You should input some simple expressions like 'a+b','a+2' **in the lower left corner of the picture above**. **Please notice** 'hello' is a key word in default grammar rules, so don't use it.
