### ISSUE TITLE
Tree export with transparent background either light text or nothing happens.

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#352]
if you leave the default and click ok during export, nothing happens. If, instead, you put ".png" at the end of the name, it now correctly generates the file. If you don't, nothing is generated, at least for Mac 10.14.2, latest of IntelliJ community edition.

<img width="1512" alt="screen shot 2019-02-04 at 12 35 19 pm" src="https://user-images.githubusercontent.com/178777/52236558-049d8a80-287c-11e9-8aed-e8428fab94ec.png">

**Comment by bjansen** [comment]
Huh, on Windows there is a select box to choose which output format you want:

![image](https://user-images.githubusercontent.com/281528/52262550-0e32fb00-292d-11e9-9ae3-aa80b8edc538.png)

But on macOS it uses a native file chooser, where there is no default extension so the plugin doesn't know what to generate. I'll add a special case for macOS, and find a way to show the user what file formats are available.

**Comment by bjansen** [comment]
OK, problem fixed. One remaining issue: users will not know which file extensions are available on macOS, because the native file chooser doesn't suggest them.

FYI, it's possible to [switch back to a Java file chooser](https://intellij-support.jetbrains.com/hc/en-us/community/posts/115000128290-Use-IDE-File-Chooser-Rather-Than-Native-One) similar to the one in the screenshot I posted in my previous comment.

**Comment by bjansen** [comment]
Maybe we could add more options to the contextual menu when we're on macOS and the native file chooser is enabled:

* export to PNG
* export to JPEG
* export to SVG
* export to transparent PNG
* export to transparent SVG

Each of these options would ‘force’ a file format in the save dialog.

**Comment by parrt** [comment]
Is it also the case that they don't know they can generate transparent background? i.e., do they see a dropdown about format? If so, maybe they would know to add the extension?  Failing that, the right-click pop with those options you mention is a good solution. :)

**Comment by bjansen** [comment]
When you right-click on the parse tree, you already know whether or not you are going to generate a transparent background:

![image](https://user-images.githubusercontent.com/281528/52356261-32c5ca80-2a34-11e9-9e2e-e9f0eabeb142.png)

What's missing on macOS is the list of possible file formats available for the chosen export (i.e. JPEG is not available for transparent backgrounds).

I could leave the default PNG extension, but then users won't know that they could also generate a JPEG or SVG file. 

OTOH, if I implement what I described in my previous comment on macOS only, there will be an "inconsistency" betwen OSes (although it might be a moot point).

**Comment by parrt** [comment]
well, what about prefilling in the text field with an extension of `file.{png,.jpg,.svg}` showing the viable options?
