### ISSUE TITLE
Generating images of parse tree

### ISSUE THREAD

**Issue by tkmitchell** [antlr/intellij-plugin-v4#358]
I am using Intellij 2018.3.6 and latest antlr and plugin. I can select the popup menu item for export to image and select a location, but it does not generate the file. Is this a known problem? I cannot find any errors being recorded anywhere.

**Comment by bjansen** [comment]
Could you go to `Help > Show Logs in explorer` and attach idea.log please?

**Comment by tkmitchell** [comment]
I am on the road now. When I get back home I can do that.

**Comment by clojj** [comment]
I can't reproduce this in 2019.1 ...the png gets exported correctly

**Comment by tkmitchell** [comment]
I was having trouble with the 2019 version and the plugin, so I downgraded to the 2018 version. I will upgrade to the 2019 and the 1.10 versions and try them.

**Comment by bjansen** [comment]
Still, if you are able to find the logs from when the issue happened, this could help me pinpoint what happened. Thanks.

**Comment by bjansen** [comment]
I'm closing the issue since it looks like it's not happening anymore, but feel free to reopen it.
