### ISSUE TITLE
Ambiguos interpretations invisible display

### ISSUE THREAD

**Issue by fedorusov** [antlr/intellij-plugin-v4#360]
May you add some visual settings to fix such cases?
It is not that comfortable to switch IDEA to light mode every time
![image](https://user-images.githubusercontent.com/33381180/59595816-30b8fa00-90ff-11e9-86e0-0f6df2e1d1d6.png)

**Comment by bjansen** [comment]
I changed the color to this one:
![image](https://user-images.githubusercontent.com/281528/59609922-9fef1800-9118-11e9-8424-3cc323b68635.png)

**Comment by bjansen** [comment]
It may be confusing because it's the same color as the borders in your example :/

**Comment by bjansen** [comment]
This is better:
![image](https://user-images.githubusercontent.com/281528/59611051-e80f3a00-911a-11e9-821b-a7c9a8ffb250.png)

**Comment by bjansen** [comment]
Fixed in 5d8e32c63e26a1afc706665ef5043ab73b01d1c9
