### ISSUE TITLE
Profiler ambiguity bug (antlr4 bug?)

### ISSUE THREAD

**Issue by fedorusov** [antlr/intellij-plugin-v4#361]
I have a simple parser
```antlr4
prog: rawStatement;

rawStatement
    : expression
    ;

chain
    : VarName memberAccess*
    ;

memberAccess
    : Dot VarName arguments?
    ;

expression
    : constant                                     #ScalarExpression
    | chain                                        #ChainExpression
    | expression op=('+' | '-') expression         #ArithmeticExpression
    | chain '=' expression                         #AssignmentExpression
    ;

constant
    : Decimal
    ;

arguments
    : '(' actualArgument? ')'
    | actualArgument
    ;

actualArgument
    : expression
    | chain
    ;
```
where lexer rules are
```antlr4
VarName:            [a-zA-Z_][a-zA-Z_0-9]*;
Decimal:            Digit+;
fragment Digit:     [0-9];
Dot:                '.';
```
and the input `abc = 1+2`. The output should be obvious, but profiler produces
![image](https://user-images.githubusercontent.com/33381180/59608323-c5325500-911d-11e9-831f-8855b102d477.png)
The issue here that I don't have any dots in the input but antlr goes to `arguments` rule. It can be spotted because after adding something to the end of memberAccess like
```antlr4
memberAccess
    : Dot VarName arguments? Dot
    ;
```
the ambiguity disappears.
Looks like antlr is looking from right to left too, going to `arguments:2` rule, then `actualArgument`, then to `expression` and finally recognizes `(abc = 1)+2` expression.

**Comment by bjansen** [comment]
I guess you could use `grun -diagnostics` like someone did in [this SO question](https://stackoverflow.com/q/39827313/500478) to check whether your problem comes from the IntelliJ plugin or from the ANTLRv4 tool itself.

**Comment by fedorusov** [comment]
```grun Ruby prog -diagnostics
a = 1+2
line 1:2 reportAttemptingFullContext d=2 (expression), input='a ='
line 1:4 reportContextSensitivity d=2 (expression), input='a = 1'
line 1:5 reportAttemptingFullContext d=3 (expression), input='+'
line 1:6 reportAmbiguity d=3 (expression): ambigAlts={1, 2}, input='+2'```
Ok this is an antlr problem, thanks
