### ISSUE TITLE
Pluging locks IJ Ultimate 2019.2 EAP

### ISSUE THREAD

**Issue by blueglyph** [antlr/intellij-plugin-v4#362]
I'm not sure this is entirely relevant, since this happens on an early access version. I'm reporting the problem in case it's interesting in order to prepare for the final release, perhaps something changed in 2019.2 that makes it incompatible with ANTLR's intellij-plugin-v4.

Tested on Win7 x64 Pro.
intellij-plugin-v4 v1.9 (both the standard one, and the one which could be downloaded in the 'refresh' issue)

**Brief description**

Since 2019.2 EAP, the whole IDE completely locks in a frozen state when opening a project with ANTLR grammar files.

**Steps to reproduce**

- opened IJ in a clean state (no project loaded)
- uninstalled intellij-plugin-v4
- opened a project with antlr grammar files
=> opens normally, the *.g4 files can be opened but have no syntax highlighting or antlr grammar language awareness

- installed intellij-plugin-v4
- restarted IJ IDE
=> the IDE opens the grammar file, syntax is highlighted, but side panels are closed, main menu or contextual menu items cannot be opened, keyboard is ineffective. The only file shown in the editor tabs is the grammar file, other Java/Kotlin files that were previously opened have no tab (as if everything stopped when opening the grammar file). A flashing red exclamation mark is visible at the bottom right but it is not possible to open the crash log with the mouse.
It is possible to place the cursor with the mouse, or even to select text, but that's about it.

The only way to close IJ is to kill the processes.
The only way to recover IJ after that is to rename the directory project so that it wouldn't try and open it again (because from that point on it's locked again).
Uninstalling the plugin removes the problem.

I tried with two different projects, a simple one in Java, another more complex in Java + Kotlin.

The same projects can be opened normally with the CE version of IntelliJ (currently 2019.1).
They could be opened normally with IntelliJ Ultimate in 2019.1 EAP.

Log attached. Alternatively, I can report that to Jetbrains, or just try again on 2019.2 final release.

[idea.zip](https://github.com/antlr/intellij-plugin-v4/files/3307376/idea.zip)

**Comment by bjansen** [comment]
It's super strange because none of the stack traces in the logs you provided are related to classes in the ANTLR plugin. I'll try to reproduce the problem on my machine to check if the problem is indeed caused by the plugin.

**Comment by blueglyph** [comment]
Perhaps it's coincidence, or maybe it's only data related to the plugin which indirectly cause the problem?

I see lines 196-314 what seems to be the start of a chain of failures to load the editor for a grammar file. But I've never written a plugin for IntelliJ, it's pure speculation on my part.

The filename 'ArrayInitLexer.g4' pops out a lot.

Near the end (lines 2823-), also this:

> 2019-06-19 20:01:01,668 [  27102]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2019.2 EAP  Build #IU-192.5281.24 
> 2019-06-19 20:01:01,668 [  27102]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
> 2019-06-19 20:01:01,668 [  27102]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 7 
> 2019-06-19 20:01:02,838 [  28272]   INFO -       ANTLRv4ExternalAnnotator - doAnnotate D:/projects/ANTLR/_archives/test/src/ex/tg/ArrayInitLexer.g4 
> 2019-06-19 20:01:03,992 [  29426]   INFO -       ANTLRv4ExternalAnnotator - doAnnotate D:/projects/ANTLR/_archives/test/src/ex/tg/ArrayInitLexer.g4 
> 2019-06-19 20:01:05,241 [  30675]  ERROR - llij.ide.plugins.PluginManager - @NotNull method com/intellij/util/ui/UIUtil.getListSelectionBackground must not return null 

I can close this if you think it's unrelated.

**Comment by blueglyph** [comment]
The main project I'm working on cannot really be uploaded, that's why I tried also on another small project, that's what produced this log. It's a bit of a mess, an old test I did long ago, but if you think that helps, I can upload it.

From what I saw the problem is immediate on any project when there is a grammar file.

**Comment by bjansen** [comment]
OK I was able to reproduce the problem and even found which line causes it :

https://github.com/antlr/intellij-plugin-v4/blob/71c8d4340c426b7ca0652ce1934ae41050486fe6/src/main/java/org/antlr/intellij/plugin/preview/UberTreeViewer.java#L38

Something must have changed in IDEA 2019.2 in the Darcula Look And Feel, maybe we are now trying to access it before it's correctly initialized. It's causing a bunch of totally unrelated exceptions anytime something tries to instantiate a Swing component or access something in the LAF. Very nasty bug.

Anyway, I'm not sure yet how I'm going to fix this, but commenting this part of the code definitely works around the problem.

**Comment by bjansen** [comment]
Could you please try this build and let me know if your project works correctly?

[intellij-plugin-v4-1.9.zip](https://github.com/antlr/intellij-plugin-v4/files/3307720/intellij-plugin-v4-1.9.zip)

It's a build of the current master branch + a few lines that I commented out.

See [this page](https://www.jetbrains.com/help/idea/managing-plugins.html#install_plugin_from_disk) to install a plugin from disk.

**Comment by bjansen** [comment]
This code was a fix for #170 to make the parse tree usable in Darcula. I found a better fix that does not require querying the look and feel, so I'm closing the issue. I'll try to schedule a release soon with @parrt

**Comment by blueglyph** [comment]
The build in intellij-plugin-v4-1.9.zip solves the problem.

Thanks for the quick investigation!
