### ISSUE TITLE
Parse tree error in dark mode

### ISSUE THREAD

**Issue by msangel** [antlr/intellij-plugin-v4#363]
Parse tree errors in dark mode is not readable as it uses light-grey-magenta error text background for white text.

![Parse tree errors in dark mode is not readable](http://i.imgur.com/wamjypS.png)

In dark mode the text background color should be like dark-grey-magenta or any other color that will make the error text readable.

**Comment by bjansen** [comment]
Unfortunately that color is hard-coded in a class from the ANTLR tool: https://github.com/antlr/antlr4/blob/master/tool/src/org/antlr/v4/gui/TreeViewer.java#L189

I'm trying to figure out a clever way to replace it.

**Comment by bjansen** [comment]
<img width="131" alt="image" src="https://user-images.githubusercontent.com/281528/60299685-98581c00-992d-11e9-9b13-bb1b658a0c8f.png">

**Comment by msangel** [comment]
Built from sources.
Yes, dark theme looks good, but ... light became broken :neutral_face:
![](http://i.imgur.com/8HGmTVs.png)
![](http://i.imgur.com/geIOtYj.png)

**Comment by bjansen** [comment]
![image](https://user-images.githubusercontent.com/281528/60325691-2d87fe80-9988-11e9-9c8f-8063b885e74c.png)

**Comment by bjansen** [comment]
Fixed again!
