### ISSUE TITLE
ANTLR Preview encoding

### ISSUE THREAD

**Issue by mheinzerling** [antlr/intellij-plugin-v4#369]
I have a UTF-8 source file and a UTF-8 grammer. According to stackoverflow this should be supported in ANTLR 4.
Nevertheless the ANTLR Preview seems not to handle my files as UTF-8 and also the Parse tree has the same issue. Where can I change the encoding for the plugin, or is this a bug, or is this me and I need to add something to my grammer.

![encoding](https://user-images.githubusercontent.com/2889071/60765459-fb1e8580-a09a-11e9-9237-596943065670.png)

**Comment by bjansen** [comment]
I need a bit more context. 
* Did you type text in the preview window, or did you load a file? 
* If you loaded a file, what encoding is it using? 
* What is your OS' default encoding?
* Could you provide a sample grammar to reproduce the bug?

**Comment by bjansen** [comment]
OK I was able to reproduce this on a Windows machine: the file is loaded using the system's default charset (in my case Windows-1252).

**Comment by mheinzerling** [comment]
Please excuse the delay. I was on vacation. If I get it right, you have everything now you need?

**Comment by bjansen** [comment]
Yes.

**Comment by mheinzerling** [comment]
@bjansen, I'm missing the big picture here. Is it valid to replace `FileUtil.loadFileText` by `LoadTextUtil.loadText` in `InputPanel.selectFileEvent()`. The later seems to have an automatic detection of the charset (or at least a fallback to UTF-8) and is used to load the grammer file in the editor?

**Comment by bjansen** [comment]
Sorry for the delay, I was on vacation. I started working on this issue in July, and took a different approach: instead of loading the file directly via `FileUtil.loadFileText`, I let IntelliJ load the `Document` automatically using `FileDocumentManager.getInstance().getDocument(inputFile)`. 
This will in turn use `LoadTextUtil.loadText` like you suggested, but I'm not sure if the correct encoding will always be detected. I need further testing to see if that would be enough.

**Comment by bjansen** [comment]
If I create a sample file within the IDE, and set this file's encoding from within the IDE, then it will be loaded with the correct encoding in the ANTLR Preview window (I believe the IDE stores the encoding information somewhere to be use later).

On the other hand, if I change the file encoding from an external application like VS Code, IntelliJ will reload the file with the wrong encoding. The main editor will see it and show a tooltip "File was loaded in the wrong encoding", but the ANTLR Preview will not. I suppose we could run the same inspection in the Preview to show a similar tooltip.

**Comment by mheinzerling** [comment]
Actually I don't know anything about IntellyJ plugin development. I was just a kind of motivated to dive into this issue yesterday :) I'm pretty sure you found the better approach. At least it is an improvement for all sample files within the project.

**Comment by bjansen** [comment]
From now on, when the file is loaded using an incorrect charset in the Preview window, open the same file in a regular editor and change the encoding to the correct value. When you switch back to the Preview window, the text will be reloaded automatically.

I haven't figured out yet how to run the inspection automatically, but that might come in the future.
