### ISSUE TITLE
Add multiline TODO to the plugin

### ISSUE THREAD

**Issue by fedorusov** [antlr/intellij-plugin-v4#370]
Hi, IDEA plugin for a custom language need a some overriding described [here](https://youtrack.jetbrains.com/issue/IJSDK-506#focus=streamItem-27-3172105.0-0) to support a proper multiline TODO highlighting. Will you add this in the future?

**Comment by bjansen** [comment]
> Your custom language should provide IndexPatternBuilder implementation, correctly overriding getCommentStartDelta/getCommentEndDelta/getCharsAllowedInContinuationPrefix. Without this platform is unable to determine what characters in a comment are delimiters, and what characters are actual text.

That should be possible to do :)

**Comment by bjansen** [comment]
Done:
<img width="216" alt="image" src="https://user-images.githubusercontent.com/281528/61077653-27316200-a41f-11e9-800d-327c3aa9a84e.png">
