### ISSUE TITLE
IntelliJ plugin does not support sets for first token definition after @header

### ISSUE THREAD

**Issue by ericvergnaud** [antlr/intellij-plugin-v4#374]
Using IntelliJ,  type the following grammar:

```
grammar PropTypesExtractor;

@header {
}

COMMENT: '//' .*? '\n' ;
WS: [ \t\r\n]+ -> skip ;

```
-> all good

now type:

```
grammar PropTypesExtractor;

@header {
}

WS: [ \t\r\n]+ -> skip ;
COMMENT: '//' .*? '\n' ;

```
IntelliJ highlights the set as 'no viable alternative'.

Only happens if there is a `@header` section

**Comment by bjansen** [comment]
The same bug exists in [grammars-v4/LexerAdaptor.java](https://github.com/antlr/grammars-v4/blob/98876a9a8b3101ea360a0febf41a228488b254ba/antlr4/src/main/java/org/antlr/parser/antlr4/LexerAdaptor.java), which the plugin's lexer is based on.
