### ISSUE TITLE
Ability to define CharStream implementation

### ISSUE THREAD

**Issue by nixel2007** [antlr/intellij-plugin-v4#376]
Hello.

I develop a antlr lexer and parser for case insensitive language.

Lexer uses rules with uppercased text:

https://github.com/1c-syntax/bsl-parser/blob/cb4f82419b38198d6ef00f647d9d3af5c7ad1d18/src/main/antlr/BSLLexer.g4#L103-L108

**CaseChangingCharStream** from antlr4 docs is used for text uppercasing while LA:

https://github.com/1c-syntax/bsl-parser/blob/master/src/main/java/com/github/_1c_syntax/bsl/parser/CaseChangingCharStream.java#L93-L102

Finally, regular CharStream is wrapped in CaseChangingCharStream:

https://github.com/1c-syntax/bsl-parser/blob/cb4f82419b38198d6ef00f647d9d3af5c7ad1d18/src/main/java/com/github/_1c_syntax/bsl/parser/Tokenizer.java#L93-L94

But ANTLR4 plugin for IDEA knows nothing about CaseChangingCharStream and uses common CharStream for lexing. As a result I can't use "antlr preview" window without uppercasing keywords manually.

My suggestion is to add some way to define CharStream used for lexing process in "configure" window (and gradle plugin settings)

Thanks!

**Comment by bjansen** [comment]
For this to work, the char stream would have to be in the IDE's classpath. Having the class in the current project would not be enough, since it wouldn't be in the IDE's execution classpath.

**Comment by bjansen** [comment]
As this is a reasonably common use-case, I guess we could ship our own version of `CaseChangingCharStream` in the plugin, and add an option to wrap `CharStream` automatically.

**Comment by bjansen** [comment]
I added a new option in the grammar settings dialog:

<img width="738" alt="image" src="https://user-images.githubusercontent.com/281528/71424928-887c8300-2697-11ea-97be-0154e6ca1a18.png">

This option is then automatically used by the Preview window to configure the `CharStream` used to lex the input.

I'm not sure the wording I used makes it obvious that the text is not actually transformed in the editor, but rather in the lexing phase.

**Comment by KvanTTT** [comment]
Maybe it makes sense to rename to `UPPERCASE` and `lowercase`? :)

**Comment by bjansen** [comment]
I changed the text to `Transform to lowercase when lexing`.
