### ISSUE TITLE
Performance issue in parsing html

### ISSUE THREAD

**Issue by chakpongchung** [antlr/intellij-plugin-v4#380]
Cannot parse the following html 

https://bulbapedia.bulbagarden.net/wiki/Ability#List_of_Abilities

using the html grammar from https://github.com/antlr/grammars-v4/tree/master/html

When I tried to generate the parse tree, the plugin in intellij 2019.03 simply stop responding.

@bjansen

**Comment by bjansen** [comment]
Could you be more specific? What grammar are you using? Do you have any errors (OutOfMemoryException maybe)?

**Comment by bjansen** [comment]
How do you generate the parse tree? Do you copy/paste HTML in the ANTLR Preview window?

**Comment by bjansen** [comment]
The same HTML document is also slow to parse from the CLI using `grun HTML htmlDocument ~/Downloads/Ability.html`, so the issue is likely due to the grammar itself, not to the IntelliJ plugin. Please open an issue at https://github.com/antlr/grammars-v4/issues instead.
