### ISSUE TITLE
Read-only Attribute of Editor Buffer not Reset

### ISSUE THREAD

**Issue by thron7** [antlr/intellij-plugin-v4#382]
I'm not sure whether this is a bug or a feature, but I'm struggling with it anyway.

When I open a file in Intellij I can edit it.

When I then open the same file in ANTLR Preview -> File, the Intellij buffer turns to read-only (which might be a feature). This is such that the lock icon in Intellij's status bar still shows "unlocked", and Intellij's File menu only offers the "Make file read-only" menu entry. It only becomes apparent when I really try to change the buffer (s. screenshot).

This read-only mode now is never removed. I cannot edit the file anymore until I restart Intellij. It doesn't help to chose a different file in ANTLR Preview or switch it to direct Input. I also found no way to reset the plugin itself.

![grafik](https://user-images.githubusercontent.com/885920/71966996-df8b6780-3202-11ea-95be-8d70973ae9bb.png)

**Comment by bjansen** [comment]
Hi, thanks for reporting the issue.

The editor in the ANTLR Preview window is read-only on purpose, but it should not affect the "main" editor in which the same file is open.

I was able to "reset" the main editor by locking then unlocking the file (even if as you noticed the file was already locked but the icon didn't show it).

**Comment by thron7** [comment]
Yep, that works for me too. I'm fine with the work-around, so if you have no further use for it you might close this issue.

**Comment by bjansen** [comment]
Well I think the bug should be fixed, because this side effect is definitely not intended.
