### ISSUE TITLE
Upgrade to ANTLR 4.8

### ISSUE THREAD

**Issue by david-29** [antlr/intellij-plugin-v4#384]
Running my application:

Command:  cal
List: a+b
Entering parseExprList() ...
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2
ANTLR runtime and generated code versions disagree: 4.8!=4.7.2

**Comment by bjansen** [comment]
Hold your horses, I think @parrt hasn't finished releasing yet. [antlr4-runtime-4.8.jar](https://repo.maven.apache.org/maven2/org/antlr/antlr4-runtime/4.8/antlr4-runtime-4.8.jar) returns a 404, so a new version 4.8-1 was released. 
We should wait for an official announcement before releasing the plugin.

**Comment by parrt** [comment]
yep official. announcing today. i also noticed a bug @bjansen where tokens w/o rulenames like `'('` get a `null:(` leaf node in the parse tree...ring any bells?

**Comment by parrt** [comment]
BTW missing 4.8 jar is some weird sonatype bug so i rereleased

**Comment by parrt** [comment]
(Note 4.8 has 4.3 ST4 in it)

**Comment by bjansen** [comment]
@parrt 

> tokens w/o rulenames like '(' get a null:( leaf node in the parse tree

Yes I think I've already seen that, it should be a simple fix.

So we should not use 4.8, but rather 4.8-1 instead, right?

**Comment by parrt** [comment]
right. 4.8-1 is the one that works.  Should be the same software but maven doesn't allow replacing versions so it's just a different build number.
