### ISSUE TITLE
Can't test rule (input window is read-only)

### ISSUE THREAD

**Issue by aleksey2000** [antlr/intellij-plugin-v4#385]
Hi!

I have following config: 
- Idea 2018.3
- Plugin version: 1.13

I'm trying to test any section in my G4 file, but it's not possible - input window for text to recognise is in read-only mode. Could you plz check?

<img width="1410" alt="Screenshot 2020-01-21 at 14 55 54" src="https://user-images.githubusercontent.com/21368107/72803092-4591d900-3c5e-11ea-83c5-613aaa89018e.png">

**Comment by bjansen** [comment]
Ugh sorry for that, I used the wrong fix for #382. I'll make a new release ASAP.

**Comment by bjansen** [comment]
You can run "Check for updates", I just released v1.13.1.

**Comment by aleksey2000** [comment]
> You can run "Check for updates", I just released v1.13.1.

Yes, now it works! Thank you for so urgent update!
