### ISSUE TITLE
Compiling auto-generated ANTLR source files results in errors, though grammar looks correct

### ISSUE THREAD

**Issue by ghost** [antlr/intellij-plugin-v4#39]
Using this grammar from the Definitive ANTLR 4 Reference:
grammar Expr;

@header {
    package org.gleason.antlr.Expr;
}

// parser rules
prog:    stat+ ;

stat:    expr NEWLINE
    |    ID '=' expr NEWLINE
    |    NEWLINE
    ;

expr:    expr ('*'|'/') expr
    |    expr ('+'|'-') expr
    |    INT
    |    ID
    |    '(' expr ')'
    ;

// lexer rules
ID      :    [a-zA-Z]+ ;
INT     :    [0-9]+ ;
NEWLINE :    '\r' ? '\n' ;
WS      :    [ \t]+ -> skip ;

The generated files resulted in these errors when attempting to compile:

`ExprParser.java:41: error: method does not override or implement a method from a supertype
    @Override
    ^
ExprParser.java:321: error: cannot find symbol
        new ATNDeserializer().deserialize(_serializedATN.toCharArray());
            ^
  symbol:   class ATNDeserializer
  location: class ExprParser
ExprParser.java:201: error: method enterRecursionRule in class Parser cannot be applied to given types;
        enterRecursionRule(_localctx, 4, RULE_expr, _p);
        ^
  required: ParserRuleContext,int
  found: ExprContext,int,int,int
  reason: actual and formal argument lists differ in length
ExprParser.java:245: error: cannot find symbol
                        if (!(precpred(_ctx, 5))) throw new FailedPredicateException(this, "precpred(_ctx, 5)");
                              ^
  symbol:   method precpred(ParserRuleContext,int)
  location: class ExprParser
ExprParser.java:261: error: cannot find symbol
                        if (!(precpred(_ctx, 4))) throw new FailedPredicateException(this, "precpred(_ctx, 4)");
                              ^
  symbol:   method precpred(ParserRuleContext,int)
  location: class ExprParser
ExprParser.java:299: error: cannot find symbol
        case 0: return precpred(_ctx, 5);
                       ^
  symbol:   method precpred(ParserRuleContext,int)
  location: class ExprParser
ExprParser.java:301: error: cannot find symbol
        case 1: return precpred(_ctx, 4);
                       ^
  symbol:   method precpred(ParserRuleContext,int)
  location: class ExprParser
ExprLexer.java:79: error: cannot find symbol
        new ATNDeserializer().deserialize(_serializedATN.toCharArray());
            ^
  symbol:   class ATNDeserializer
  location: class ExprLexer
ExprLexer.java:51: error: method does not override or implement a method from a supertype
    @Override
    ^
9 errors`

Going through the compilation process from start to finish by generating the code with with the normal ANTLR4 tool and then compiling with `javac` works just fine.... no errors. I am not sure why it wouldn't work with IntelliJ; I have made sure ANTLR4 jar file is added as a library for the project....

**Comment by AnushaGarg** [comment]
Experiencing same problem...with 100 errors and I m using ANTLR 4.5.3

**Comment by ctminh** [comment]
Hi AnushaGarg,

Maybe you have some mistakes in the command of compiling your project:
$ javac -d ../Sample/bin -cp $CLASSPATH:$ANTLR_JAR:../Sample/bin ./target/generated-sources/antlr4/*.java

After $CLASSPATH you have to indicate $ANTLR_JAR, I have the same problem with you. And I fixed it.
