### ISSUE TITLE
Add pattern matching fileName in ANTLRv4GrammarPropertiesStore#findSettingsForFile

### ISSUE THREAD

**Issue by bintom** [antlr/intellij-plugin-v4#390]
currently there is only exact file matching, I would suggest adding matching using Java pattern

**Comment by bjansen** [comment]
For this to work, you would have to modify settings manually in `.idea/misc.xml`, so I'm not sure how that would help. What exactly would you like to do?

**Comment by bintom** [comment]
Yes I would like to modify `.idea/misc.xml` manually. In project we are using parser generators in `main` and `test` scope. I would like to define two patterns  with different target directories to be sure all grammars will be generated in correct locations. In many projects people are sharing various `.idea` files to be sure configuraion is the same for all developers.

This feature is backward-compatible with current exact-match solution, so I think it will be useful for advanced users.

Currently, there is a `fileName` with value `*` as a default location and it is a default for all grammars. I would like to add here any working java pattern, e.g. `.*test.*\.g4` would match any file with `test` in its fileName with suffix `.g4`. For files matching more than one pattern I suggest to raise an ERROR.

**Comment by bjansen** [comment]
How about this:

* first try to find an exact name match, like it is currently doing
* if no result was found, try to find the first settings that match the file name

I'm not sure why you want to raise an error (and where: in the logs? show a message box?). Keep in mind that this method is also called when modifying the settings via the UI, so in this case a log will not be helpful. On the other hand, I don't think a message box will be great when raising an error during parser generation.
