### ISSUE TITLE
Use ANTLR Preview with standalone lexer

### ISSUE THREAD

**Issue by gquerret** [antlr/intellij-plugin-v4#397]
The grammar I'm working with has a standalone lexer (for various reasons such as include file management, preprocessing, abbreviated keywords, ...). Is there a way I can pass the output of this lexer (which implements 
org.antlr.v4.runtime.TokenSource) to the parser, and see the result in the hierarchy and profiler tabs ?

**Comment by bjansen** [comment]
By "standalone lexer", you mean its not generated by ANTLR from a grammar?

If that's the case, then there is no way to use this lexer from the IDE. The hierarchy/profiler work by interpreting grammars, they don't actually run generated code. Moreover, the plugin only has access to the IDE classpath, and can't load classes from projects classpaths.

For this to work, I guess you need something similar to ANTLRWorks' debugger, although I'm not sure that feature still exists for ANTLRv4 grammars.

**Comment by gquerret** [comment]
> By "standalone lexer", you mean it's not generated by ANTLR from a grammar?

Yes, it's written by hand

> If that's the case, then there is no way to use this lexer from the IDE.

At first, I thought it could be possible to modify the plugin's code to inject the output of the custom TokenStream, but if it's not possible to access the project classpath, then I'll find another way.
Thanks !

**Comment by gquerret** [comment]
A last question regarding the modification of the plugin: my lexer doesn't have any outside dependency (and I can remove the unneeded parts such as the preprocessor), and produces a TokenStream. As I just want to analyze ambiguities in the parser (the lexer is stable), do you think it is doable to plug my lexer in the plugin ? I was thinking about ParsingUtils#parseText(...).

**Comment by bjansen** [comment]
I suppose that would be technically possible, if you fork and build a custom version of the plugin.

Another more "official" solution: the plugin could declare an extension point for other plugins to provide their own lexer. But then the difficulty is to know when to use which lexer.
