### ISSUE TITLE
IntelliJ crashes after writing a certain parser rule with EOF.

### ISSUE THREAD

**Issue by 7we** [antlr/intellij-plugin-v4#399]
**NOTE:** The steps below may crash IntelliJ.

Steps to recreate:

- Use version 2020.1.2 EAP, it may or may not occur on other versions. Using Pop!_OS Linux. 
- Use the sample grammar below.
```
grammar Test;

sourceTest: thing* EOF;

thing: '\r' | '\n' | EOF;
```
- Select the rule set `sourceTest` in the ANTLR preview.

IntelliJ will stop responding. I've personally tested this 5 times with the same result each time; if I'm missing any relevant variables, please let me now.

**Comment by 7we** [comment]
I see there is already an issue with seemingly the same problem.

https://github.com/antlr/intellij-plugin-v4/issues/393

**Comment by 7we** [comment]
It's unclear to me whether the fix has been implemented yet. I'm going to assume it has not been and close this.

**Comment by bjansen** [comment]
The problem has been fixed, but the fix has not been released yet. I'll schedule a release in the coming days.
