### ISSUE TITLE
the Paser tree of the plugin  runs an wrong behavior using the tour/Data.g4 example

### ISSUE THREAD

**Issue by a524631266** [antlr/intellij-plugin-v4#401]
My plugin version:
![image](https://user-images.githubusercontent.com/14838935/86422702-66338400-bd10-11ea-8536-cddd79cfd424.png)
the wrong show about the parse tree:
![image](https://user-images.githubusercontent.com/14838935/86422729-7d727180-bd10-11ea-8cc3-239c9e0faf7b.png)
Showing the picture, that the tokens: "3 1 2 3" cannot be splitted into a group.  
my test using runtime tools:
![image](https://user-images.githubusercontent.com/14838935/86422739-89f6ca00-bd10-11ea-82cf-bb75f53280e0.png)
Showing the picture , that the  tokens: "3 1 2 3" can be correctly splitted into a new group.  

Why does the Paser tree fo Plugin showing the result that beyond my understanding?

**Comment by bjansen** [comment]
Hi,

The ANTLR Preview window is based on an interpreter, it does not actually run the real lexer/parser that are generated from your grammars. This means that custom lexers and predicates like `{$i < $n}?` will be ignored by the interpreter.
