### ISSUE TITLE
IntelliJ Syntax Highliting shows errors in Apache spark grammar, which runs fine. 

### ISSUE THREAD

**Issue by theodiefenthal** [antlr/intellij-plugin-v4#403]
I just opened the ANTLR4 grammar from Apache Spark in IntelliJ with the latest ANTLR plugin
 (Cloudera Fork, but probably the same as root): https://github.com/cloudera/spark/blob/cdh6.3.1/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4 

in the file editor, the plugin highlights a lot of failures:
<img width="1587" alt="spark-failures" src="https://user-images.githubusercontent.com/4670569/88289765-0704d600-ccf6-11ea-8b33-cc1e6a05e45d.png">

However, the syntax is running productively and fine. Even the preview works fine with the file:
![grafik](https://user-images.githubusercontent.com/4670569/88289850-28fe5880-ccf6-11ea-87a1-10be8055bb7e.png)

So I suspect there to be something wrong with the Syntax checker in the plugin here

**Comment by bjansen** [comment]
`options` on line 88 is incorrectly recognized as a keyword, causing the parser to completely lose its mind :)

Sorry for the regression.
