### ISSUE TITLE
Test ANTLR Rule - option dead

### ISSUE THREAD

**Issue by maifeeulasad** [antlr/intellij-plugin-v4#411]
For some reason my **Test ANTLR Rule** option is dead.

I was working on separate devices, it was dead in one. When it was available in other.

![Screenshot (1444)](https://user-images.githubusercontent.com/29339330/92015384-81535c00-ed72-11ea-98c7-fe8c02ac5f93.png)

**Comment by bjansen** [comment]
Are you right-clicking on a valid parser rule?

**Comment by maifeeulasad** [comment]
First of all, grammar is correct.

It's behaving differently on different PC, I will submit details configuration of both as soon as possible.

**Comment by maifeeulasad** [comment]
For some reason this works on :
```
IntelliJ IDEA 2020.2.1 (Ultimate Edition)
Build #IU-202.6948.69, built on August 25, 2020
Licensed to IntelliJ IDEA Evaluator
Expiration date: October 2, 2020
Runtime version: 11.0.8+10-b944.31 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.4.0-45-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Non-Bundled Plugins: org.antlr.intellij.plugin
Current Desktop: ubuntu:GNOME
```
And doesn't work in : 
```
IntelliJ IDEA 2019.1
(more details will de added soon)
```

**Comment by bjansen** [comment]
Does your rule name start with a lowercase character?

**Comment by maifeeulasad** [comment]
Just line this *Test.g4* : 
```
grammar Test;

test : '{' someBlock '}';
```

**Comment by bjansen** [comment]
Sorry, but I can't reproduce this problem so I can't fix it. Are you still experiencing it?

**Comment by maifeeulasad** [comment]
@bjansen I'm sorry to say that, I don't have that Windows machine right now. If I ever encounter again, I'll talk here, maybe. I'll try to check all those versions from git to my local Ubuntu machine and try to reproduce.

**Comment by bjansen** [comment]
@maifeeulasad what should we do with this issue? Are you still seeing the bug?

**Comment by maifeeulasad** [comment]
@bjansen please close this, cause I'm getting that windows machine no time soon. If I ever get that machine I'll update here for sure. 

And in my Linux machine I couldn't reproduce this issue.

**Comment by bjansen** [comment]
Ok 👌
