### ISSUE TITLE
Highlight .g4 file not working in Pycharm CE 2020.2.2

### ISSUE THREAD

**Issue by luosh18** [antlr/intellij-plugin-v4#414]
As title described, I am currently using Pycharm CE 2020.2.2, but the highlight of .g4 file just doesn't work.
Wondering if it's the problem of Pycharm Version because it's mentioned that the plugin works with 2016.1-2019.3 Jetbrains IDEs.
Hopes that it can be fixed or there exists a method to enable highlight.
Thanks.

**Comment by bjansen** [comment]
Hi, the readme is slightly outdated, the plugin should work in recent versions (at least it works in IDEA 2020.2.3 on my machine). Can you see errors in the logs? (Help > Show Logs)

**Comment by bjansen** [comment]
@luosh18 are you still experiencing the problem?

**Comment by luosh18** [comment]
No, I switch to 2020.2.3 and it functions normally. Sorry for replying late. Thank you.

**Comment by bjansen** [comment]
OK, I'll close the issue. Feel free to reopen and attach logs if the problem happens again.
