### ISSUE TITLE
Lexer not using semantic predicates

### ISSUE THREAD

**Issue by ternarycup** [antlr/intellij-plugin-v4#416]
i've ran into an issue where semantic predicates defined in a lexer g4 file are not evaluated in the plugin. i see that generated lexer.java does contain {_input.LA(1)!='!'} in the corresponding _sempred method; however when i use "test rule" feature from ANTLR Preview, that code is ignored. if i run the code in Java and parse sample input - i do see that semantic predicate is properly used, as expected.

not sure if this is called out anywhere in the documentation - reporting as a bug, as i didn't notice it.

**Comment by kaby76** [comment]
I also ran across this, having noticed the parse trees are not the same between this plugin and "grun". I now see [issue #161](https://github.com/antlr/intellij-plugin-v4/issues/161). "No raw Java actions are executed obviously during interpretation in live preview." It's not really obvious. No Actions ("{ ... }") and no Semantic predicates ("{ ,,, }?") are executed. Use grun, via "alias grun='java org.antlr.v4.gui.TestRig'", to display the tree with semantic predicates executed.

**Comment by ternarycup** [comment]
will close this issue - thank you for calling out #161 
i do think that this should be a bit more emphasized under "features/limitations"

**Comment by kaby76** [comment]
My mistake: "Action" is used for both "{ ... }" and "{ ... }?" syntactic features (https://github.com/antlr/antlr4/blob/master/doc/actions.md). Sorry for the mix-up.

**Comment by bjansen** [comment]
Right, this is something we could emphasize in the readme, and perhaps also in the preview window.

**Comment by bjansen** [comment]
Done: https://github.com/antlr/intellij-plugin-v4/blob/master/README.md#limitations

**Comment by kaby76** [comment]
Yes, that will probably work. But, you know nobody reads the doc. It would be best if the code that generates the Java file in the plugin just checks for the presence of ARG_ACTION within the grammar file, and then give warnings.

**Comment by ternarycup** [comment]
> Done: https://github.com/antlr/intellij-plugin-v4/blob/master/README.md#limitations

thanks!
