### ISSUE TITLE
Plugin takes a lot of time or does not start at all

### ISSUE THREAD

**Issue by IceMikl** [antlr/intellij-plugin-v4#419]
Hi Antlr team,

Thank you very much for this parser generator and a plugin for it!

Sometimes it takes a lot of time to start the plugin or it will be not started at all in Intellij Community. To fix it I clean cache and restart the IDE. What could be a cause? How it could be fixed?

With best regards,
Mikl

**Comment by bjansen** [comment]
Hi, 

What do you mean exactly by "start the plugin"? The plugin is automatically started with the IDE. Do you mean it takes time to test a parsing rule and show the preview results?

**Comment by IceMikl** [comment]
Hi @bjansen ,

I mean that sometimes, when I start Intellij Community the plugin will be not "clickable" however the Intellij was started and there no active "preparation" processes in it. Therefore it seems that ANTLR plugin needs a lot of time to be ready to work. Or someting happens in it.

I tried to replicate the error, but it works properly. If it will repeat, I will add the screenshot.

**Comment by IceMikl** [comment]
Hi @bjansen ,

I have found the issue. When I switched to the "new" branch, the ANTLR has information about the grammar in the "old" branch and for this reason it didn't work. 
So it was not an issue.

**Comment by bjansen** [comment]
All right, thanks for the update :)
