### ISSUE TITLE
Cannot designate the target antlr4 version for the generated sources

### ISSUE THREAD

**Issue by kingspider1971** [antlr/intellij-plugin-v4#423]
We cannot upgrade the antlr4 component frequently in the production environment. We hope that the plugin could provide the feature to specify the target antlr4 version by the users.

**Comment by bjansen** [comment]
The plugin embeds a given version of ANTLR (usually the latest), which is used to highlight errors in the editor, run the Preview window, and of course generate sources from the IDE. It is not possible to change the version of generated sources. 

If your project is using Maven or Gradle though, it is entirely possible to use an older version of their respective ANTLR plugin to generate your parsers. The latest ANTLR will be used to edit grammars and run previews, and an older ANTLR will be used to generate sources.

For example :
* IntelliJ plugin v1.15 and ANTLR **v4.9** 
* `antlr4-maven-plugin` **v4.7**

**Comment by bjansen** [comment]
@kingspider1971 did you test my suggestion?

**Comment by kingspider1971** [comment]
Your suggestion is feasible. I use the plugin to edit grammar files, and write a OS shell script to generate the target sources.

**Comment by kingspider1971** [comment]
Your suggestion is feasible. I use the plugin to edit grammar files, and write a OS shell script to generate the target sources.
