### ISSUE TITLE
Support for separate lexer grammar and parser grammar?

### ISSUE THREAD

**Issue by xpe** [antlr/intellij-plugin-v4#425]
Does this plugin support having both a lexer grammar and a parser grammar?

If so, what do I need to do to make things work as smoothly as possible?

```g4
lexer grammar FooLexer
// and so on...
```

```g4
parser grammar FooParser
options { tokenVocab = FooLexer; }
// and so on ...
```

**Comment by bjansen** [comment]
Hi,

It's briefly mentioned in the readme:

> handles separate parsers and lectures like TParser.g4 and TLexer.g4 (1.7)

The plugin itself uses the technique you described: https://github.com/antlr/intellij-plugin-v4/blob/master/src/main/antlr/org/antlr/intellij/plugin/parser/ANTLRv4Parser.g4#L37

**Comment by bjansen** [comment]
Both grammars need to be in the same directory BTW.

**Comment by xpe** [comment]
@bjansen Thanks for the reply. 

Also, I got it to work. 

Here was my problem: I had moved a file using the command line, so CLion did not aware of it, causing some data in the `.idea` directory to become stale / invalid.

To fix (as a hack), I deleted the `.idea` directory and restarted CLion. Now, with the defaults, things are working fine.

\* Side note, based on a quick search, it seems likely that Java cannot portably detect file renames.

**Comment by kremec** [comment]
> Both grammars need to be in the same directory BTW.

Does the same still stand today? I have Lexer.g4 in one directory and Parser.g4 in another one, and when i use tokenVocab=Lexer, I get errors and no autocomplete for tokens from lexer...
