### ISSUE TITLE
Problem with highlighting rules in g4 files in Intellij 2020.3.1

### ISSUE THREAD

**Issue by Grucha8** [antlr/intellij-plugin-v4#426]
After updating my Intellij to 2020.3.1 plugin stopped highlighting rules usage when cursor is on that rule (as seen on screen below).
![image](https://user-images.githubusercontent.com/33691675/104178672-04fd1380-540b-11eb-9142-df2168c07d6e.png)
Before the highlighting worked similar like the one in java classes (see screen below).
![image](https://user-images.githubusercontent.com/33691675/104179002-7fc62e80-540b-11eb-9d65-ffd35a14b976.png)
I don't know if the problem is on my side (some option in Intellij that I didn't turned on) or simply a bug in plugin.
If it is a bug then is there a chance that you will fix it?

**Comment by bjansen** [comment]
Hi, I've noticed the same thing, it's probably a bug but I haven't had time to fix it yet.
