### ISSUE TITLE
"ANTLR preview" becomes grey and unusable

### ISSUE THREAD

**Issue by nmz787** [antlr/intellij-plugin-v4#429]
sequence:
* open "ANTLR preview"
* load a large file
* start looking through parse tree
  * See an error in the `parser.g4`
  *  fix error
  * rebuild lexer and parsers from the command-line with:
    * `"C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\jbr\bin\java.exe" -Xmx500M -cp "C:\Users\myuser\Downloads\antlr-4.8-complete.jar" org.antlr.v4.Tool C:\Users\myuser\git\myproject\mynamespace\mytoolname\parsers\parser_flavor\Lexer.g4 -Dlanguage=Python3`
    * `"C:\Program Files\JetBrains\PyCharm Community Edition 2020.1\jbr\bin\java.exe" -Xmx500M -cp "C:\Users\myuser\Downloads\antlr-4.8-complete.jar" org.antlr.v4.Tool C:\Users\myuser\git\myproject\mynamespace\mytoolname\parsers\parser_flavor\Parser.g4 -Dlanguage=Python3`
* head back to "ANTLR preview", expecting to reload the file or refresh
  * find a greyed out window, with apparently nothing I can do to recover it aside from restarting PyCharm

**Comment by bjansen** [comment]
The preview is disabled when you switch from a .g4 file to any other file. When you come back to a .g4 file, it's re-enabled. This has already been discussed in #409, you're very welcome to give your thoughts on the topic. The current behavior doesn't feel right, and I guess a lot of newcomers are lost when they see the preview is disabled.

**Comment by nmz787** [comment]
No this feels like a crash, as the last step is me returning to the same parser G4 file and the plugin just not ever responding until I close PyCharm and restart the IDE completely.

**Comment by bjansen** [comment]
Could you attach the IDE logs that were generated when it happened? (Help > Show logs)

**Comment by parrt** [comment]
ping @nmz787
