### ISSUE TITLE
Feature Request - Test Lexer Rules

### ISSUE THREAD

**Issue by nmz787** [antlr/intellij-plugin-v4#430]
Lexer rules can't be tested, but having them work correctly is fundamental to having a parser rule work.

I was able to code Python unit tests for the lexer rules, to aid in my development and debug:
https://gist.github.com/nmz787/cf98aa465a4d071a937cf74788687a54

but it was quite unexpected that the visual plugin couldn't do this.

**Comment by bjansen** [comment]
I think #417 is the same request as yours? If there was a new tab in the right part of the preview, showing the list of tokens that were lexed, would that be enough?

**Comment by bjansen** [comment]
@nmz787 is it something like this you're looking for? https://github.com/antlr/intellij-plugin-v4/issues/417#issuecomment-766168222

**Comment by bjansen** [comment]
Closing as duplicate of #417

**Comment by nmz787** [comment]
I don't think #417 is the same thing. #417 wants to see tokens associated with a specific parser rule. This ticket (430) is about wanting lexer tokens, without having written a parser.
