### ISSUE TITLE
Feature Request - do not hide "ANTLR Preview" when switching to lexer

### ISSUE THREAD

**Issue by nmz787** [antlr/intellij-plugin-v4#431]
When debugging, I often need to review and fix bugs in the lexer, but when I switch to the lexer while testing a parser rule, the ANTLR preview window goes blank (hides the file contents that were loaded) and I cannot interact with the parse hierarchy (it is greyed out).

Please disable this functionality, as it makes debug and development take much longer.

**Comment by bjansen** [comment]
That's the same problem as #429, right?

**Comment by nmz787** [comment]
No, this is the same as 409.
