### ISSUE TITLE
Preview is not displayed

### ISSUE THREAD

**Issue by ligun** [antlr/intellij-plugin-v4#447]
I installed the plugin on IntelliJ IDEA, and wrote a simple grammar.
But the plugin displayed nothing preview. Grayed out when I right-clicked and show menu.
How can I fix it?

## Environment
* OS Microsoft Windows10 Pro 2004
* IDE IntelliJ IDEA UE 2020.03
* ANTLR v4 Plugin 1.16

I develop using Java and Gradle.
build.gradle is here.

```
plugins {
    id 'groovy'
    id 'antlr'
}

group 'foo'
version '0.1-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    antlr 'org.antlr:antlr4:4.9.1'
    testImplementation 'org.codehaus.groovy:groovy-all:3.0.7'
    testImplementation 'org.spockframework:spock-core:2.0-M4-groovy-3.0'
}

```

Grammar file is here.

```
// Define a grammar called Hello
grammar Hello;

r  : 'hello' ID ;         // match keyword hello followed by an identifier
ID : [a-z]+ ;             // match lower-case identifiers
WS : [ \t\r\n]+ -> skip ; // skip spaces, tabs, newlines
```

ANTLR Preview tab showed the message. `Hello.g4 start rule: <select from navigator or grammar>`

**Comment by bjansen** [comment]
The message is telling you to select a start rule to preview: in the editor, right-click on your `r` rule and select `Test rule`. Then you can enter an input text in the preview window to actually test the rule.

**Comment by ligun** [comment]
Thank you for your reply!
Now, I understood how I can execute it.
