### ISSUE TITLE
Feature request: disable plugin functionality other than syntax highlighting

### ISSUE THREAD

**Issue by nmz787** [antlr/intellij-plugin-v4#450]
I don't trust the plugin, and it often crashes PyCharm with my large files (hundreds of megabytes, if not gigabytes).

I enjoy the syntax highlighting.

I would like to be able to disable all functionality except for syntax highlighting. Or maybe you can point me to a PyCharm plugin that only includes the syntax highlighting.

Thanks.

**Comment by bjansen** [comment]
See my answer here: https://github.com/antlr/intellij-plugin-v4/discussions/446#discussioncomment-614064
