### ISSUE TITLE
Generator doesn't honor Python 3 minor versions using `typing.io` imports

### ISSUE THREAD

**Issue by PeterTillema** [antlr/intellij-plugin-v4#477]
When you run "Generate ANTLR Recognizer..." the lexer output file has 
```python3
from typing.io import TextIO
```

in its header, while doing it yourself yields
```python3
if sys.version_info[1] > 5:
	from typing import TextIO
else:
	from typing.io import TextIO
```

The upper one is clearly wrong, as it's dependent on the minor version of Python 3.

**Comment by bjansen** [comment]
This looks like a different version between what's shipped in the plugin and what you're using when you generate the parser yourself. The header you're mentioning was [introduced in february](https://github.com/antlr/antlr4/commit/f7b4100fcc7da61044475bbd22fdf54052fe55e5) and released in ANTLR 4.9.2 according to GitHub.
The IntelliJ plugin is still shipping ANTLR 4.9.1, I'll prepare a new version with the latest ANTLR.
