### ISSUE TITLE
Class not found: javax.swing.JPanel

### ISSUE THREAD

**Issue by borneq** [antlr/intellij-plugin-v4#480]
Execution failed for task ':instrumentCode'.
> Forms instrumentation failed for /home/andrzej/gitmy/intellij-plugin-v4/src/main/java/org/antlr/intellij/plugin/configdialogs/ConfigANTLRDialogPanel.form: : /home/andrzej/gitmy/intellij-plugin-v4/src/main/java/org/antlr/intellij/plugin/configdialogs/ConfigANTLRDialogPanel.form: Class not found: javax.swing.JPanel

**Comment by bjansen** [comment]
I take it you're trying to build the plugin from source. This can happen if you're trying to build with an unsupported JDK version. For example, if `ideaVersion=IC-2017.1.6` in `gradle.properties` then you need a JDK 8 IIRC. If you want to use a JDK 11, switch to a more recent version of IDEA, something like `ideaVersion=IC-2020.3`.

**Comment by bjansen** [comment]
I updated the readme accordingly: https://github.com/antlr/intellij-plugin-v4/commit/18a7d2215aee6f5b3ed69b6bf3153b7b09304b0f
