### ISSUE TITLE
strange error messages when running rule in plugin while it's working when invoking via command line

### ISSUE THREAD

**Issue by jgehw** [antlr/intellij-plugin-v4#487]
I encounter strange error messages when running rules in PyCharm 2021.1.2 via ANTLR v4 plugin 1.17 (v4.9.2), while they are working fine when running them via command line.

Steps to reproduce:
- download example [Python3.g4](https://github.com/antlr/grammars-v4/blob/master/python/python3-py/Python3.g4)
- set language to "Python3" in "Configure ANTLR..." settings
- click "Generate ANTLR Recognizer"
- run "Test Rule" on rule "file_input"
- provide some python code as input, e.g.
```
def func(a, b):
    return a + b
```
- observe strange error messages:
```
line 1:3 extraneous input ' ' expecting NAME
line 1:11 mismatched input ' ' expecting {'*', ')', '**'}
line 1:13 mismatched input ')' expecting {NEWLINE, ';'}
line 2:14 extraneous input ' ' expecting {STRING, NUMBER, 'None', 'True', 'False', 'await', NAME, '...', '(', '[', '+', '-', '~', '{'}
```

To verify that it's not a bug in the provided example:
- install Python packge `antlr4-python3-runtime` with the same version (v4.9.2)
- download [pygrun](https://github.com/jszheng/py3antlr4book/blob/master/bin/pygrun)
- invoke via `pygrun Python3 file_input --tree input.txt` where `input.txt` contains the same test code used above
- no errors are issued + correct tree is printed

As I did **not** regenerate the recognizer via command line (`java org.antlr.v4.Tool -Dlanguage=Python3 Python3.g4`) but used the output generated by the intellij plugin, we can conclude that it's neither a bug in the generation process. Thus, the bug must be somewhere in the part of the intellij plugin handling execution of a rule.

Unfortunately, I don't have a smaller gammar to trigger the bug; several other, simpler examples I tried didn't produce these errors.

I don't know how to debug intellij plugins. Maybe it's even faster to review the code that launches execution of a rule; maybe it's just a minor error in parameter passing, environment variables, or input encoding.

Please let me know if you need further information, or how I can help identify the root cause.

**Comment by bjansen** [comment]
Hi @jgehw 

The Preview window runs an _interpreter_, not the actual generated parser. This is [documented in the readme](https://github.com/antlr/intellij-plugin-v4#limitations), and it boils down to the fact that it would be hard and possibly unsafe to execute generated parsers in the same process that is running the IDE. Running the generated parser in a separate process could do the trick (especially if the target language is not Java!), but then I don't think there would be a way to extract all the information that we gather from the interpreter (like parse trees, tokens, perf data etc).

So what you are seeing is "normal". Your Python grammar contains predicates, like in the `NEWLINE` rule. Predicates are completely ignored by the interpreter, which is probably why the input can't be parsed correctly.

**Comment by jgehw** [comment]
Hi @bjansen 

Sorry, I missed this particularly important piece of information. Thanks for pointing me there.

To verify that this was the only problem and no secondary errors following, I slightly changed the grammar such that it skips the indentation check implemented in the predicates. This only requires two rule changes:
```
// suite: simple_stmt | NEWLINE INDENT stmt+ DEDENT;
suite: simple_stmt | NEWLINE stmt+;
...
NEWLINE : '\r'? '\n' | '\r' | '\f' | '<EOF>';
```

With this change I can use the intellij plugin and benefit from its great features during development, and finally revert the changes for the final version.

I'm wondering if ANTLR has a language feature that allows detection of running in an interpreter. This would eliminate the necessity of manually en-/disabling these parts of the grammar, and would be a nice supplement to the example in case others are stumbling upon the same error. I'm looking for something like (pseudocode):
```
#ifdef __INTERPRETER__
    suite: simple_stmt | NEWLINE stmt+;
    NEWLINE : '\r'? '\n' | '\r' | '\f' | '<EOF>';
#else
    suite: simple_stmt | NEWLINE INDENT stmt+ DEDENT;
    NEWLINE
     : ( {self.atStartOfInput()}? SPACES
       | ( '\r'? '\n' | '\r' | '\f' ) SPACES?
       )
       {self.onNewLine()}
     ;
#endif
```
Do you know how to achieve this?

**Comment by parrt** [comment]
There's no way to determine where it's running, particularly because of all of the different language targets we have.  Yeah, I can't think of a good option for executing raw code... it is possible that we could come up with a listener that did this but it won't be a high priority for me. Thanks for the report but I will close this for now.

**Comment by KvanTTT** [comment]
> I'm wondering if ANTLR has a language feature that allows detection of running in an interpreter. This would eliminate the necessity of manually en-/disabling these parts of the grammar, and would be a nice supplement to the example in case others are stumbling upon the same error. I'm looking for something like (pseudocode):

I don't think it's a good solution to use different grammar depending on running mode.

> Yeah, I can't think of a good option for executing raw code... it is possible that we could come up with a listener that did this but it won't be a high priority for me.

It's possible to implement even with debugging but it's quite complicated and it requires configured runtime. We have something similar in ANTLR runtime tests. I don't think a listener is required here.
