### ISSUE TITLE
No syntax highlighting and "Test ANTLR Rule" disabled on PyCharm 2021.3.1 (Professional Edition)

### ISSUE THREAD

**Issue by eirikur-grid** [antlr/intellij-plugin-v4#509]
Hi there. I'm, running into a weird issue using the ANTLR plug-in in PyCharm 2021.3.1 on macOS (Big Sur).
I can configure it for my grammar, select the target language (Python3) and run the "Generate ANTLR Recognizer" action without any problems. However, there's no syntax highlighting and I can't use the "Test ANTLR Rule" action.

![antlr-pycharm](https://user-images.githubusercontent.com/50045006/156730330-4f603edb-bbc5-46c2-9efb-28ec6095e71e.gif)

I've tried uninstalling the plugin and then re-installing it but that didn't help. However, if I open the same project/directory in either

 - PyCharm 2020.3 (Community Edition)
 - IntelliJ 2021.3.1 (Community Edition)

it works like a charm! (no pun intended)

**Comment by bjansen** [comment]
@eirikur-grid could you attach your `idea.log` please (Help > Show Logs)? It looks like something goes wrong during IDE startup.

**Comment by MalekiRe** [comment]
I have the same issue on Linux

**Comment by wolframdeus** [comment]
Same for me. WebStorm 2021.3.3

**Comment by flowrider3000** [comment]
Same issue here on IntelliJ IDEA 2021.3.3 (Ultimate Edition) and MacOS

**Comment by parrt** [comment]
Hi. Could try the zip here https://github.com/antlr/intellij-plugin-v4/issues/495#issuecomment-1059977763 ? We'll push a new version soon.

**Comment by parrt** [comment]
Hmm...just tried on Linux inside google and it worked with 1.17 and 1.18. BUT, another googler with same linux box and intellij it did not work for either!!!

**Comment by bjansen** [comment]
Is the `g4` extension correctly registered as ANTLR grammar in `Preferences | Editor | File and Code Templates`?

**Comment by eirikur-grid** [comment]
> Is the g4 extension correctly registered as ANTLR grammar in Preferences | Editor | File and Code Templates?

I presume you meant `File Types`, rather than `File and Code Templates`. 

The `File Types` list is interesting. In the problematic version (PyCharm 2021.3.1 Professional) then I can see an entry for "ANTLR v4 grammar file" but the "File name patterns" list is empty! Rather surprisingly, `*.g4` is listed under the "Text" file type.

In my PyCharm 2020.3 Community installation, I see `*.g4` correctly listed for "ANTLR v4 grammar file"

**Comment by eirikur-grid** [comment]
For me, the issue is solved by removing `*.g4` from the "Text" file type and adding it to the "ANTLR v4 grammar file" type

**Comment by parrt** [comment]
Ok, I just found a place related to file type mapping they used a deprecated API; working on updating that.
