### ISSUE TITLE
Add option to pin to a specific ANTLR version

### ISSUE THREAD

**Issue by edoardopirovano** [antlr/intellij-plugin-v4#512]
The project I'm working on is pinned to a specific version of the ANTLR run-time which is older than the one this plugin uses for code generation. So, I get the following warning when running things using this plugin:

```
ANTLR Tool version 4.9.2 used for code generation does not match the current runtime version 4.7.2
```

It would be nice if the plugin supported pinning to a specific version of ANTLR for code generation - for example, by having a configuration option that lets you specify a path to the JAR to use.

**Comment by parrt** [comment]
Unfortunately, I think we can only hook the plug-in to a specific version of antlr.

**Comment by parrt** [comment]
I guess I will close this as I can't think of a way to handle this. Sorry! Probably its best done with your build tools anyway for your application.
