### ISSUE TITLE
In readme, Limitations should note parse trees are not the same as standard parser output 

### ISSUE THREAD

**Issue by kaby76** [antlr/intellij-plugin-v4#519]
In [Limitations](https://github.com/antlr/intellij-plugin-v4#limitations), it should be noted that the tree produced by the tool "interpreter" is not not same as what is produced by a standard generated parser. See [this](https://stackoverflow.com/questions/71698815/antlr4-error-recovery-issues-for-class-bodies?noredirect=1#comment126760328_71698815).

**Comment by kaby76** [comment]
And, since the wonderful crop of software developers don't know how to read documentation, it's best to output a warning on parse error. The warning should go in the "ANTLR Preview" pane, indicating that the trees may not be what one sees with a generated parser.

**Comment by parrt** [comment]
Is this only because of actions / predicates? Should be the same tree being displayed otherwise

**Comment by kaby76** [comment]
I think a warning in the doc for the plugin will suffice. No need to change the code.

**Comment by parrt** [comment]
ok. thanks.
