### ISSUE TITLE
Cannot use Syntactic Predicates

### ISSUE THREAD

**Issue by ericlentz** [antlr/intellij-plugin-v4#521]
Adding a => to a grammar produces an error.

As an example, grab [b.g](http://media.pragprog.com/titles/tpantlr/code/synpred/b.g) from The Definitive ANTLR Reference code examples. It produces an error in the plug-in, but should not, of course.

The syntax is (rule)=>rule and serves to disambiguate rules, giving a precedence to a rule. It is quite important if you have ambiguity.

**Comment by KvanTTT** [comment]
This syntax and grammar are only valid for ANTLR 3. Plugin uses ANTLR 4.
