### ISSUE TITLE
ANTLR v4 plugin does not support antlr4-python3-runtime 4.10 yet

### ISSUE THREAD

**Issue by thesamy2704** [antlr/intellij-plugin-v4#529]
ANTLR v4 seems not to support the latest version of antlr4-python3-runtime (v4.10) ( see https://pypi.org/project/antlr4-python3-runtime/#history) yet. I had issues with the installation using PyCharm.

**Comment by bjansen** [comment]
I'm going to release 1.18 soon, which will upgrade to 4.10.1
