### ISSUE TITLE
UI freeze after parse on SQL grammars with large inputs

### ISSUE THREAD

**Issue by Endeavourl** [antlr/intellij-plugin-v4#546]
I'm trying to profile my SQL grammar on a large input with diverse statements, which used to go fine in previous versions some years ago.
I managed to consistently reproduce a UI freeze that seems to happen *after* parsing of the input is finished.
Looking at the CPU load, there's a ~15s multithreaded parser spike and then a single thread becomes pinned at 100% and UI freezes.
Considering this and #381 it seems that the issue is with displaying parsing/profiling results. And it happens even when disabling every option on the left of the preview panel (auto-update, parse-tree etc).

Repro:
Use [example PostgreSQL grammar](https://github.com/antlr/grammars-v4/tree/master/sql/postgresql) or [my PostgreSQL grammar](https://github.com/pgcodekeeper/pgcodekeeper/blob/master/apgdiff/antlr-src/SQLParser.g4).
Test `root` rule (`sql` rule in my grammar).
Concat every [example SQL](https://github.com/antlr/grammars-v4/tree/master/sql/postgresql/examples) into a single file, i used this command: `find *.sql | xargs -I{} sh -c "cat {}; echo ''" > _concat.sql`.
Use the new, ~2.9MB file as ANTLR Preview input.
Note UI freeze after a short delay (parse stage). UI doesn't unfreeze for at least 10 minutes, process has to be killed.

**Comment by bjansen** [comment]
Hi, thanks for reporting the problem and for the reproducible case. Not sure how to handle this one. There might be ways to improve the situation, like parsing in a (possibly cancellable) background thread instead of the UI thread. 
Have you tried parsing this rather huge file with `grun` directly? Depending on how the grammar is written, if the parsing itself is slow there's not much we can do to make it faster. Avoiding UI freezes should be possible, but there's no guarantee that the background thread won't still take 10min to process the file. 
Also I'm not sure how the IDE will react when it has to render the parsing results in the preview window. This has to be done in the UI thread anyway.

**Comment by KvanTTT** [comment]
> There might be ways to improve the situation, like parsing in a (possibly cancellable) background thread instead of the UI thread.

Unfortunately, currently ANTLR doesn't support cancellation: https://github.com/antlr/antlr4/issues/2274

**Comment by Endeavourl** [comment]
The issue is not cancelability, obviously such large input is expected to produce some *temporary* UI stutter. Right now though it completely hangs in what seems to be an infinite loop. I let the process run for an hour and it didn't recover. It didn't run out of memory either.
In earlier (ca. 2019) plugin versions this kind of test worked ok, completing UI render in about a minute or so.

I tried running my grammar with `grun` method, it required removing java package lines from the `@header` sections, but otherwise worked fine. Parser took several seconds, and it even rendered the graph UI, obviously laggy but somewhat responsive.

To me this seems like an infinite loop somewhere in ANTLR Preview UI code, when it fills the parse result data.

**Comment by parrt** [comment]
I'm pretty sure that the tree visualization is the issue; it's either nonlinear or mildly so. I wonder if we could simply put the tree construction in a separate thread and kill it if it takes too long? I ran into this issue myself recently.

**Comment by bjansen** [comment]
@KvanTTT we could do something like override `org.antlr.v4.runtime.ParserInterpreter#visitState` and throw an exception when needed ;)

**Comment by Thracky** [comment]
Would like to add my +1 to this issue and note that I am seeing it on a grammar of similar complexity and a much smaller input, only about 310 KB.

**Comment by parrt** [comment]
hi. I totally agree. I'm going to try to solve this hopefully this weekend. The basic problem is that the tree layout mechanism is nonlinear and I stupidly build the tree picture using the GUI thread I think.  Upon keystroke, I need to initiate thread worker to build the Picture but it must kill any Picture construction that is going on already. I don't think this has anything to do with parsing speed canceling the parse. @bjansen does that sound reasonable?

**Comment by parrt** [comment]
Hi. @Thracky @Endeavourl Can you guys try a snapshot of 1.19
[antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip](https://github.com/antlr/intellij-plugin-v4/files/8645790/antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip)
?

**Comment by Endeavourl** [comment]
Hangs exactly like the stable version for me.

**Comment by parrt** [comment]
Dang. i tried it on java grammar and big input. had no problem. Well, it's slow parsing like 8s but doesn't freeze.  You sure it installed correctly?

**Comment by parrt** [comment]
I'm happy to get your grammar and input if public...

**Comment by parrt** [comment]
Confirmed. 76k lines kills it. Hmm...*should* work...investigating.

**Comment by parrt** [comment]
Heh @KvanTTT other than kotlin compiler do you work on plugins? hint hint haha  I can't trace this gui thread blocking thing.

**Comment by KvanTTT** [comment]
No, at least not yet :)

**Comment by parrt** [comment]
Ok, I have confirmed that not even the simple treeview from a main program works for displaying the tree from 76k lines of SQL. The GUI immediately freezes after I tried to draw:

```
$ grun SQL sql -gui < /tmp/all.sql 
```

That is with 76k lines. It seems to work "OK" with 5000 lines of sql.

Anyway, I just don't think the GUI freezing is our problem.  Displaying millions of no it's just not some thing that swing with set up for.

I'm going to try to smooth out how we handle displaying the tree but Java swing just can't handle this and put @Endeavourl sorry!

**Comment by parrt** [comment]
Ok, i give up. Even with tree building totally turned off, the GUI thread spins for 5k lines. Tried all sorts of stuff. :(

**Comment by parrt** [comment]
Holy crap!  It looks like it's the token view text field, which has, maybe, 800k lines given 76k input lines of SQL.  @bjansen it's `TokenStreamViewer` I think.  If I comment that out, it takes all 76k SQL lines. A bit sluggish but works, even in intel emulation mode for M1 mac.

**Comment by parrt** [comment]
Ok, I believe I have now fixed it!  @bjansen @Thracky @Endeavourl Can you guys try a snapshot of 1.19?  Input should be much more responsive. Delay is about 1s if you stop typing in 76k sql input and it updates tree.

[antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip](https://github.com/antlr/intellij-plugin-v4/files/8690662/antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip)

**Comment by parrt** [comment]
Fixed by https://github.com/antlr/intellij-plugin-v4/pull/551

**Comment by parrt** [comment]
Ok, I believe I have now fixed it! @bjansen @Thracky @Endeavourl Can you guys try a snapshot of 1.19? Input should be much more responsive. Delay is about 1s if you stop typing in 76k sql input and it updates tree. (I posted one about an hour ago that was wrong. This is the correct one.)

[antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip](https://github.com/antlr/intellij-plugin-v4/files/8691177/antlr-intellij-plugin-v4-1.19-SNAPSHOT.zip)

**Comment by parrt** [comment]
Still not perfect for huge input but great for a few thousand :)

**Comment by Endeavourl** [comment]
Thanks, works as expected now!
