### ISSUE TITLE
Bug closing non-active grammar file

### ISSUE THREAD

**Issue by parrt** [antlr/intellij-plugin-v4#559]
Open two grammars T1.g4 and T2.g4.  Show T1.g4 but click close box on T2.g4 which closes the T1.g4 preview pane and when you reopen, it's dehighlighted and inactive.

<img width="844" alt="Screen Shot 2022-05-21 at 2 09 09 PM" src="https://user-images.githubusercontent.com/178777/169669048-208a4246-5beb-4883-9a62-b3f2d8abca09.png">

Must close/open grammar to get correct preview.

<img width="858" alt="Screen Shot 2022-05-21 at 2 10 18 PM" src="https://user-images.githubusercontent.com/178777/169669088-66e963e6-c1de-49de-afde-8d0c84947e8f.png">

Gotta be a weird thing like *killing the wrong previewState based upon active window not the one being closed*.

**Comment by kjarrio** [comment]
Fixed w/ unit tests in PR #574
