### ISSUE TITLE
Can not jump to usage code

### ISSUE THREAD

**Issue by zhuxt2015** [antlr/intellij-plugin-v4#562]
idea:2022.1.1 Ultimate Edition
ANTLR V4 plugin: 1.19.2
<img width="479" alt="image" src="https://user-images.githubusercontent.com/13765310/170803771-7d82b60e-9ef0-428d-b3e8-29e8e7fab282.png">
<img width="374" alt="image" src="https://user-images.githubusercontent.com/13765310/170803782-639ead76-b149-42aa-bd06-2fee63ca8967.png">

**Comment by parrt** [comment]
Could I get your grammar to try out?

**Comment by parrt** [comment]
BTW, jump to token def only seems to work in single X.g4 files.

**Comment by zhuxt2015** [comment]
> Could I get your grammar to try out? Was a single grammar or XParser.g4 and XLexer.g4?
That's the g4 file, Modify the file suffix to g4 [StarRocks.txt](https://github.com/antlr/intellij-plugin-v4/files/8792601/StarRocks.txt)

**Comment by parrt** [comment]
Works for me with 2021.3.3. Will try new intellij.

**Comment by parrt** [comment]
Works in IntelliJ IDEA 2022.1.1 (Ultimate Edition).  Are you trying on token or rule?
