### ISSUE TITLE
faulty grammar + using preview consumes all heap

### ISSUE THREAD

**Issue by hans-d** [antlr/intellij-plugin-v4#566]
Using:
- IntelliJ Ultimate 2022.1.2
- Antlr4 plugin 1.19.2

Running on Macbook M1

As soon as the preview is being used, the memory (heap) usage becomes exhausted in no time. Currently set at 4096 MB.
Looks like #275

**Comment by parrt** [comment]
Weird. Can you show us the grammar and input?

**Comment by parrt** [comment]
Do you get antlr tool warnings/errors in the ANTLR console?

**Comment by hans-d** [comment]
Use the following:
```
grammar faulty;

file
    : (TEXT1 | TEXT2)*
    ;

 TEXT
    :
    ;
```
No tool output.

**Comment by parrt** [comment]
Ah. You'll notice a warning in antlr console (empty alt in `*` loop).  Hit the parse cancel button on left of preview panel I think :)

**Comment by parrt** [comment]
(the empty alt is a warning not error as grammar can still be useful other than that piece)

**Comment by hans-d** [comment]
Havent noticed that warning, but did notice that intellij became very
slow/sluggish, complaining about memory.

Op za 11 jun. 2022 om 19:38 schreef Terence Parr ***@***.***>

**Comment by KvanTTT** [comment]
Probably it's related to ANTLR core not to plugin.

**Comment by parrt** [comment]
Actually I take that back. That shouldn't do anything other than give an error, so I will take a look.

**Comment by parrt** [comment]
Ok, i get: `Empty or bad grammar in file Foo.g4` in the tool output.
