### ISSUE TITLE
Antlr plugin reports error about the grammar

### ISSUE THREAD

**Issue by oraluben** [antlr/intellij-plugin-v4#582]
grammar: https://github.com/antlr/grammars-v4/blob/master/golang/GoParser.g4

The plugin reports the following error:
![image](https://user-images.githubusercontent.com/5031346/184783955-cc6ffb3a-072b-4db0-8237-cd253b5791ac.png)

While manually running Antlr to generate parser succeeds, changing the line a little bit also makes the error disappear.
![image](https://user-images.githubusercontent.com/5031346/184784096-0f62ff88-7e69-49da-8b11-4cffff91306b.png)

**Comment by parrt** [comment]
Weird. statement or eos must be optional somehow?

**Comment by oraluben** [comment]
This seems more like a bug in the grammar, after updating to the latest version the error's gone:
```
statementList: ((SEMI? | EOS? | {this.closingBracket()}?) statement eos)+;
```
https://github.com/antlr/grammars-v4/blob/fb3f94261f15260172f2d8a4a7bce8b5467e3725/golang/GoParser.g4#L82
I'm not closing this (but feel free to do so) because it's still confusing me why the plugin show error but when running Antlr CLI it succeeds (only with warnings).

**Comment by parrt** [comment]
Hmm...must be different antlr version then?

**Comment by oraluben** [comment]
could be... I'm using a v4.9.2.
