### ISSUE TITLE
spark sql test rule error

### ISSUE THREAD

**Issue by zheng594** [antlr/intellij-plugin-v4#587]
Error is as follows，cannot recognize lowercase letters

![image](https://user-images.githubusercontent.com/11880516/192778893-a4838b2a-46ad-4425-ad25-08722a0bc5ae.png)

**Comment by parrt** [comment]
no idea. maybe there's no lexer?

**Comment by bjansen** [comment]
As explained by @jiang13021, it works fine on uppercase text:

<img width="1363" alt="image" src="https://user-images.githubusercontent.com/281528/228601672-ece910c0-9f9a-4359-b19c-6ea360b788fd.png">

And also when enabling "Transform to uppercase when lexing".
