### ISSUE TITLE
please update ANTLR version to 4.11.1

### ISSUE THREAD

**Issue by scrumbest** [antlr/intellij-plugin-v4#588]
ANTLR 4.10.1 does not support golang well

**Comment by parrt** [comment]
on my list! :)

**Comment by parrt** [comment]
Fixed by 5a21ecf5d811e60c546cb7ffec9d2060607901a1

**Comment by parrt** [comment]
it's out. can you try to update plugin?

**Comment by scrumbest** [comment]
Yes, Thanks a lot

> it's out. can you try to update plugin?
