### ISSUE TITLE
`intellij-plugin-v4` does not parse `expr` with precedence parameters correctly

### ISSUE THREAD

**Issue by hengxin** [antlr/intellij-plugin-v4#596]
I use `intellij-plugin-v4` (version 1.19.3-3)  to test the following `ExprPrec` grammar which is obtained by rewriting `Expr` using precedence parameters.
However, it produces wrong parse trees for inputs such as `1 * 2 + 3;`:

![parseTree](https://user-images.githubusercontent.com/1913003/204481152-a44dc689-9863-4d11-8020-1fd620b49afc.png)

The two grammars ([ExprPrec](https://github.com/courses-at-nju-by-hfwei/compilers-antlr/blob/main/src/main/antlr/parser-allstar/expr-precedence/LRExprPrec.g4), [Expr](https://github.com/courses-at-nju-by-hfwei/compilers-antlr/blob/main/src/main/antlr/parser-allstar/expr-precedence/LRExpr.g4)) are as follows:
```
grammar ExprPrec;

stat : expr[0] ';' EOF;

expr[int _p]
    : (  INT
       | ID
      )
      (  {4 >= $_p}? '*' expr[5]
       | {3 >= $_p}? '+' expr[4]
      )*
    ;

ID : [a-z] ;
INT : [0-9] ;
WS  : [ \t\n\r]+ -> skip ;
```

```
grammar Expr;

stat : expr ';' EOF;

expr : expr '*' expr
     | expr '+' expr
     | INT
     | ID
     ;

ID : [a-z] ;
INT : [0-9] ;
WS  : [ \t\n\r]+ -> skip ;
```

**Comment by bjansen** [comment]
Hi,

As [explained in the readme](https://github.com/antlr/intellij-plugin-v4#limitations), this plugin does not run predicates in the Preview window. Things like `{4 >= $_p}?` will simply be ignored, which is why the preview might not look like what you would expect.
