### ISSUE TITLE
Antlr Preview tree creates the tree based on the entire lexer

### ISSUE THREAD

**Issue by Ajris** [antlr/intellij-plugin-v4#615]
Hi,

I have found an issue with the preview tree.

If i get the simplest grammar, for instance:
![image](https://user-images.githubusercontent.com/10548910/222748280-4543be33-ed89-417e-81d9-ffd26f255be3.png)

And the simplest lexer with some obsolete values:
![image](https://user-images.githubusercontent.com/10548910/222748506-75089af3-bd3f-4cab-a5dd-1943a6189dbe.png)

I would have seen an error in a preview:
![image](https://user-images.githubusercontent.com/10548910/222748600-6d1444f8-fd0b-4060-9f94-1f8b8b19a5df.png)

After removing the obsolite line from the lexer (so the line with NOT_SOMETHING), I am finally seeing the correct results:
![image](https://user-images.githubusercontent.com/10548910/222748848-c1478868-62b4-49ca-86e1-49cfb706e213.png)

I believe that the tree shouldnt show the elements from the Lexer which are not used (they should be completely disregarded) and not considered in the preview tree.

**Comment by parrt** [comment]
I don't see why it should ignore things that match the input. Does NOT_SOMETHING match? It looks like it does to me and then you get a parse error.

**Comment by Ajris** [comment]
Because they are not in the grammar yet they are available in the lexer. Isnt only the grammar evaluated in the plugin? If the grammar doesn't use the NOT_SOMETHING in any way, should it be still showed in the tree?  I thought that the plugin can help me understand the grammar - so I would expect it compare it to the grammar that I have provided and evaluate all the rules based on the grammar that i have presented (especially if its possible) and not compare it with additional keywords that I might have specified

**Comment by parrt** [comment]
Well this is not a filtering tool. All characters that are not tokens get flagged as an error. All other tokens get sent to the parser. If the person doesn't recognize some thing it causes an error. Imagine you build a parser for a programming language that accepts any kind of random crap that doesn't happen to be Java or whatever. Not what you want ;)
