### ISSUE TITLE
Latest release of the plugin is 4.12, but 4.13 released 3 months ago.

### ISSUE THREAD

**Issue by kaby76** [antlr/intellij-plugin-v4#656]
The latest release of the plugin is out of date with the latest release of Antlr. It's been 3 months since the release (then, May 21 2023; now Aug 22 2023).

Note, the version of what tool to use should be abstracted from the plugin.

**Comment by bjansen** [comment]
I just published version 1.21, which ships ANTLR 4.13.1.
The plugin can't work without ANTLR, so we have no choice but to bundle it inside the plugin.
