### ISSUE TITLE
error(31):  ANTLR cannot generate java code as of version 4.13.1

### ISSUE THREAD

**Issue by amryounis** [antlr/intellij-plugin-v4#668]
"generate ANTLR recognizer" produces this error.

2023-10-17 14:09:26: antlr4 -o C:\Users\xxx\Desktop\hello -Dlanguage=java -listener -visitor -lib C:\Users\xxx\Desktop\hello C:/Users/ayounes/Desktop/hello\Expr.g4
error(31):  ANTLR cannot generate java code as of version 4.13.1

**Comment by bjansen** [comment]
I think you need to use `Java` with an uppercase J. Also, this problem is not related to the IntelliJ plugin, you should open an issue here: https://github.com/antlr/antlr4 if the problem persists.
