### ISSUE TITLE
Clone this plugin to quickly fix errors

### ISSUE THREAD

**Issue by zoulejiu** [antlr/intellij-plugin-v4#683]
Hi
   It looks like this plugin is not very actively maintained, so I cloned it and made some bug fixes
Plug-in address:[Antrl(New)](https://plugins.jetbrains.com/plugin/23446-antlr-v4-new-)

**Comment by bjansen** [comment]
If you open PRs on this repository, we could integrate your fixes here.

**Comment by zoulejiu** [comment]
The version I repaired is already open source, and the address is this: https://github.com/mbtsp/intellij-plugin-v4
I do a lot of deprecated code updates
and bug fixes
