### ISSUE TITLE
Issues with parser and/or lexer grammar(s) prevent preview

### ISSUE THREAD

**Issue by mburbidg** [antlr/intellij-plugin-v4#687]
My grammar is split into separate parser and lexer files(grammars). I can paste these into the ANTLR Lab and parse strings in the grammar. I can also generate Go code from these grammar files and parse strings using the resulting code.

But when I use the IntelliJ plug-in, I get the following message in the Parse-tree pane:

Issues with parser and/or lexer grammar(s) prevent preview; see ANTLR Tool Output pane.

There is nothing in the ANTLR Tool Output pane.

The grammar files are in the following repository: https://github.com/mburbidg/gqlgrammar

**Comment by bjansen** [comment]
OK I guess a more explicit error should appear somewhere, in this particular case it's because you used `grammar GQLParser;` instead of `parser grammar GQLParser;`.

**Comment by mburbidg** [comment]
Oh wow. How simple. Thank you for looking at this!
