### ISSUE TITLE
antlr4 plugin on intellij eap isn't colorizing parser source

### ISSUE THREAD

**Issue by greenhull** [antlr/intellij-plugin-v4#691]
parser source isn't being colorized in intellij eap version info:

IntelliJ IDEA 2024.1 EAP (Ultimate Edition)
Build #IU-241.10840.26, built on February 1, 2024
Licensed to IntelliJ IDEA EAP user: Chester John
Expiration date: March 2, 2024
Runtime version: 21.0.2+13-b346.3 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048M
Cores: 16
Registry:
  ide.balloon.shadow.size=0
  editor.focus.mode.color.light=e0861f
  editor.focus.mode.color.dark=e0861f
  debugger.new.tool.window.layout=true
  ide.new.editor.tabs.vertical.borders=true
  ide.animate.toolwindows=true
  ide.experimental.ui=true
  ide.editor.tab.selection.animation=true
  idea.ignore.disabled.plugins=true
Non-Bundled Plugins:
  com.intellij.javafx (1.0.4)
  org.antlr.intellij.plugin (1.23)
  Gradle View (4.0.0)
  com.godwin.json.parser (1.7.1)
  com.intellij.properties.bundle.editor (241.10840.7)
  org.sylfra.idea.plugins.linessorter (1.0.1)
  net.seesharpsoft.intellij.plugins.csv (2.21.0)
  com.dubreuia.tool (2.6.2)
  com.zt.json-editor (2.9.1)
  String Manipulation (9.12.0)
  tarn.gradle.dependencies (1.6.2)
  GrepConsole (12.23.0-IJ2023.3)
  com.chylex.intellij.inspectionlens (1.3.1)
  PlantUML integration (7.5.1-IJ2023.2)
  com.github.platan.gradle-dependencies-formatter (0.6.1)
  com.yiycf.plugins.mavenDependencyHelper (2.5)
  com.gluonhq.plugin.intellij (2.8.6)
  MavenRunHelper (4.27.1-IJ2022.2)
  izhangzhihao.rainbow.brackets (2024.1.0-233)
  com.chrisrm.idea.MaterialThemeUI (8.13.2)
  org.mallowigi.idea.MaterialThemeUI.HighContrast (2024.1.1)
  com.github.affishaikh.kotlinbuildergenerator (2.0.0)
  GradleDependenciesHelper (1.16)
  org.sonarlint.idea (10.3.0.77475)
  com.mallowigi (95.0.0)
  zielu.gittoolbox (500.1.9+222)
  com.kn.diagrams.generator.generator (2022.2.0)
Kotlin: 241.10840.26-IJ

**Comment by RGarrido03** [comment]
I'm facing the same problem.
