### ISSUE TITLE
`ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon

### ISSUE THREAD

**Issue by bjansen** [antlr/intellij-plugin-v4#696]
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.actions.ConfigureANTLRAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)

```

**Comment by oovm** [comment]
I have the same error, all my highlights are invalid

**Comment by bjansen** [comment]
@oovm I think the two problems are unrelated. I fixed syntax highlighting in 2024.1 EAP and published a new version `1.23.1`. Could you try it and see if it fixes your highlighting problem?

**Comment by oovm** [comment]
It should be that an exception was thrown that interrupted lexer's lexical highlighting. After the update, antlr highlighting returned to normal.

**Comment by yaohwu** [comment]
<img width="1411" alt="image" src="https://github.com/antlr/intellij-plugin-v4/assets/9320666/6c0f1df3-6b02-4cb3-a6ff-15dc0e62a1c7">
same happened in 1.23.1 plugin and IntelliJ IDEA 2024.1 (Ultimate Edition)

**Comment by 447491480** [comment]
same error
![image](https://github.com/user-attachments/assets/638a3b24-46c3-4771-bc6e-fd6f4a041026)

**Comment by bwinters** [comment]
some additional info from IntelliJ idea.log:

ANTLR 4 Plugin version 1.23.1, Java version 21.0.3
IntelliJ IDEA 2024.2  Build #IU-242.20224.300
JDK: 21.0.3; VM: OpenJDK 64-Bit Server VM
OS: Windows Server 2022

getting the message for 

- org.antlr.intellij.plugin.actions.GenerateParserAction
- org.antlr.intellij.plugin.actions.ConfigureANTLRAction
- org.antlr.intellij.plugin.actions.TestRuleAction
- org.antlr.intellij.plugin.actions.GenerateLexerRulesForLiteralsAction

**Comment by swnck** [comment]
Please release the current 1.23.2 because nothing works with the current 1.23.1 version.

**Comment by bjansen** [comment]
@swnck what's not working in your case? The message above is just a warning  and afaik does not prevent anything from working as expected. Besides, I haven't finished fixing the problem entirely, so releasing the current version would not solve anything.

**Comment by lppedd** [comment]
Thanks for pushing the new version! I'm not seeing the EDT messages anymore.
