### ISSUE TITLE
ANTLR Preview should let users configure which start rule to use

### ISSUE THREAD

**Issue by autonomousapps** [antlr/intellij-plugin-v4#707]
Given a grammar with multiple start rules (for example, [Kotlin](https://github.com/Kotlin/kotlin-spec/blob/release/grammar/src/main/antlr/KotlinParser.g4#L11-L17)), the ANTRL Preview window can show an error when the input doesn't match the default start rule (how is that even determined?). In the screencap below, the Preview window is trying to parse my input as if it were a `kotlinFile`, but actually it should match from another start rule, a `gradleScript` (see below for my currently internal customizations of the official grammar). The only way I have discovered to get the preview to work is to comment out the other start rules, let the preview work, and then uncomment them again; at that point, the window "remembers" (?) the correct start rule. **It would be really great if I could tell it from where to start parsing.**

<img width="916" alt="Screenshot 2024-06-24 at 11 35 53 AM" src="https://github.com/antlr/intellij-plugin-v4/assets/5402301/8f8fe4c8-cfa7-4fb7-a6f7-93e11c746aeb">

```g4
// These are the only changes to the official grammar
// NEW
gradleScript
    : NL* fileAnnotation* importList (statement semi?)* EOF
    ;

// NEW
namedBlock
    : name LCURL NL* statements NL* RCURL
    ;

// NEW
name
    : Identifier
    ;

// MODIFIED
statement
    : namedBlock // this part is NEW
    | (label | annotation)* (declaration | assignment | loopStatement | expression)
    ;
```

**Comment by minesunny** [comment]
first you should right click the rule name you want to start, then you click test rule, it should be work;

**Comment by autonomousapps** [comment]
A-ha! That worked. Thanks! <3

<img width="395" alt="Screenshot 2024-06-28 at 11 23 15 AM" src="https://github.com/antlr/intellij-plugin-v4/assets/5402301/e4a00953-4e79-462d-86fc-96380306ce17">

Closing as resolved (not sure how this might be better documented 🤷 ).
