### ISSUE TITLE
ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.preview.CancelParserAction' must override getActionUpdateThread() and chose EDT or BGT

### ISSUE THREAD

**Issue by baso4** [antlr/intellij-plugin-v4#716]
com.intellij.diagnostic.PluginException: ActionUpdateThread.OLD_EDT is deprecated and going to be removed soon. 'org.antlr.intellij.plugin.preview.CancelParserAction' must override getActionUpdateThread() and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: org.antlr.intellij.plugin] at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23) at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90) at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125) at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21) at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201) 

IDE: 
IDEA IntelliJ IDEA 2024.2.1 (Ultimate Edition)
Build #IU-242.21829.142, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 aarch64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.lwawt.macosx.LWCToolkit
macOS 14.6.1
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 12
Metal Rendering is ON
Registry:
  ide.experimental.ui=true
  i18n.locale=
  editor.minimap.enabled=true
Non-Bundled Plugins:
  PlantUML integration (7.10.1-IJ2023.2)
  org.antlr.intellij.plugin (1.23.1)
  MavenRunHelper (4.28.0-IJ2022.2)
  com.microsoft.tooling.msservices.intellij.azure (3.92.0-2024.2)
  com.baomidou.plugin.idea.mybatisx (1.6.3)
  com.github.copilot (1.5.21.6667)
Kotlin: 242.21829.142-IJ

plugin version:
[1.23.1](https://plugins.jetbrains.com/plugin/7358-antlr-v4/versions/stable/501581)

**Comment by bjansen** [comment]
Duplicates #696
